import type { Metadata } from "next";

export const metadata: Metadata={title:"Kaynaklar ve Teknik Dayanak",description:"RealHoroscope hesaplamasında ve editoryal içeriğinde kullanılan birincil astronomi, takımyıldız ve konum kaynakları.",alternates:{canonical:"/kaynaklar"}};
const refs=[
  ["Türkiye il merkezi koordinatları", "81 il merkezinin koordinatları; enisbt/turkey-cities, MIT lisansı. İlçe veya hastane konumu yerine il merkezi kullanılır.", "https://github.com/enisbt/turkey-cities"],
  ["IANA Time Zone Database", "Yerel saatlerin tarihsel UTC karşılıkları; uygulama tarayıcının saat dilimi verisini kullanır.", "https://www.iana.org/time-zones"],
  ["International Astronomical Union — The Constellations","IAU'nun 88 resmi takımyıldızı ve gökyüzü sınırlandırmasının kurumsal çerçevesi. Bağlantı IAU'nun resmî arşiv sayfasıdır.","https://iauarchive.eso.org/public/themes/constellations/"],
  ["Astronomy Engine","Güneş, Ay, yıldız zamanı ve koordinat hesaplamalarında kullanılan açık kaynak kütüphane. Bu sürüm 2.1.19 ile test edildi.","https://github.com/cosinekitty/astronomy"],
  ["OpenStreetMap Nominatim","Kullanıcının yazdığı yer adını enlem ve boylama dönüştüren açık coğrafi kodlama servisi.","https://nominatim.org/release-docs/latest/api/Search/"],
  ["NASA — Moon Phases","Ay fazlarının geometrisi ve aydınlanma döngüsünü açıklayan eğitim kaynağı.","https://science.nasa.gov/moon/moon-phases/"],
  ["Encyclopaedia Britannica — Precession","Ekinoksların presesyonu ve koordinat çerçevesindeki uzun dönem değişim için genel başvuru.","https://www.britannica.com/science/precession-of-the-equinoxes"],
];
export default function SourcesPage(){return <main id="ana-icerik" className="page-main"><div className="page-narrow"><header><p className="eyebrow">İzlenebilir bilgi</p><h1 className="display mt-3 text-4xl sm:text-6xl">Kaynaklar ve teknik dayanak</h1><p className="lede mt-5">Kaynakları sonuç üretme, kavram açıklama ve coğrafi veri sağlama rollerine göre belirtiyoruz. Ticari astroloji blogları astronomik iddialar için birincil kaynak kabul edilmez.</p></header><div className="mt-9 grid gap-4">{refs.map(([name,desc,url])=><article key={url} className="panel p-6"><h2 className="text-xl font-bold">{name}</h2><p className="mt-2 text-sm text-slate-300">{desc}</p><a className="mt-4 inline-block text-sm font-bold text-violet-200" href={url} target="_blank" rel="noreferrer">Kaynağı aç ↗</a></article>)}</div><section className="prose mt-12"><h2>Kaynak seçme standardı</h2><p>Astronomik bir iddiada kurum dokümanı, kütüphane kaynak kodu veya bilim iletişimi yapan kamu kuruluşu tercih edilir. Astrolojik yorumlar “sembolik yorum” olarak etiketlenir ve astronomik gerçek gibi sunulmaz.</p><h2>Düzeltme politikası</h2><p>Hesaplama veya kaynak hatası bildirildiğinde yeniden üretilebilir örnek istenir; tarih, UTC, koordinat ve beklenen sonuç karşılaştırılır. Doğrulanan düzeltmeler yöntem sayfasındaki sürüm notuna işlenir.</p></section></div></main>}
