import type { Metadata } from 'next';
import { FullLink as Link } from '@/components/full-link';
import { ZodiacDiagram } from '@/components/zodiac-diagram';
import { AxisMethod } from '@/components/axis-method';
export const metadata:Metadata={title:'Aks Nedir? Kök, Gölge ve Ay Duygu Ekseni',description:'Kök Aks, Gölge Aks ve Karanlık Ay ne anlatır? Yükselenin, Güneş’in ve Ay’ın karşıt noktalarının anlamını ve Ay düğümlerinden farkını öğrenin.',alternates:{canonical:'/gorsel-aks'}};
const axes=[
 {title:'Kök Aks · Saklı potansiyel',question:'İçimde hangi yetenekler yeniden keşfedilmeyi bekliyor?',text:'Kök Aks, yükselen noktanızın gökyüzündeki tam karşısında bulunan noktadır. Yükselen ile Kök Aks’ı birleştiren çizgi, bu iki yönü birlikte okumamızı sağlar. Yükselen tarafı, bir ortama girişinizi, ilk tepkinizi ve dışarıya sunduğunuz tavrı anlatır. Kök Aks ise çoğu zaman sahip olduğunuz hâlde fark etmediğiniz potansiyeli anlatır. Geçmiş deneyimlerden kazandığınız, zamanla kullanılmadığı için sönük kalmış yetenekler bu alanda ele alınır. Burada söz konusu olan eksik bir özelliği başkasından almak değil, kendi birikiminizi yeniden tanımaktır. Yükselen görünür tavrınızı, Kök Aks ise bu tavrın gerisinde yeniden değerlendirebileceğiniz yetenekleri anlatır.'},
 {title:'Gölge Aks · Kimlik ve kabul',question:'Kendimde hangi yönü öne çıkarıyor, hangisini kabul etmekte zorlanıyorum?',text:'Gölge Aks, Güneş’in gökyüzündeki tam karşısında bulunan noktadır. Güneş–Gölge Aks hattı, Güneş ile bu karşıt noktayı birleştiren çizgidir. Güneş tarafı, bilinçli olarak sahiplendiğiniz nitelikleri temsil eder. Karşı uç, kendinize yakıştırmadığınız veya başkalarında görünce sert tepki verdiğiniz özellikleri araştırmak için kullanılır. Gölge sözcüğü kötülük anlamına gelmez; henüz tanımadığınız veya ölçülü kullanmayı öğrenmediğiniz bir yönü anlatır.'},
 {title:'Karanlık Ay Aksı · Ay burcunun gölgesi',question:'Duygusal olarak neye tutunuyorum; zıddıyla karşılaşınca ne öğreniyorum?',text:'Ay burcu, mevcut duygu yapınızı, güven ihtiyacınızı ve kendiliğinden verdiğiniz duygusal tepkileri anlatır. Karanlık Ay Aksı ise Ay’ın tam 180° karşısındaki noktadır: bu platformun yorumunda Ay burcunuzun gölgesini, duygusal zıddınızı ve karşılaşıp aşmanız gereken içsel sınavı temsil eder. Ay size tanıdık gelen duygusal düzeni gösterirken, Karanlık Ay Aksı kabul etmekte zorlandığınız karşıt ihtiyacı görünür kılar. Bu ikisini birbirine bağlayan hattın adı Ay Duygu Ekseni’dir. Sonuçtaki Karanlık Ay Aksı burcu, bu yüzleşmenin hangi nitelikler üzerinden yorumlandığını belirtir. Amaç Ay burcunuzun özelliklerini reddetmek değil; karşıt niteliği de tanıyarak duygusal bütünlük geliştirmektir. Karanlık Ay Aksı burada Lilith, Ay apojesi, yeniay veya Ay düğümü anlamına gelmez; ayrı bir karşıt nokta hesabı ve sembolik yorumdur.'},
];
export default function VisualAxisPage(){return <main id="ana-icerik" className="page-main"><div className="site-shell"><header className="max-w-3xl"><p className="eyebrow">Haritanızı bir bütün olarak okuyun</p><h1 className="display mt-3 text-4xl sm:text-6xl">Aks Nedir?</h1><p className="lede mt-4">Aks, haritanızdaki iki karşıt yönü birleştiren çizgidir. Bir yerleşim tek bir ihtiyacı anlatırken, aks bu ihtiyacın karşısındaki niteliği de gösterir. Böylece yalnızca “Ben nasılım?” sorusuna değil, “Nerede denge kurmaya ihtiyacım var?” sorusuna da bakarsınız.</p></header>
 <div className="mt-6 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="panel p-4"><ZodiacDiagram/></div><section className="panel p-6"><h2 className="display text-2xl">Çemberi nasıl okuyacaksınız?</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm text-slate-300"><li>Merkezde Dünya yer alır. Çizgiler, Dünya’dan bakılan gökyüzü yönlerini gösterir.</li><li>Güneş simgesini takip edin: Güneş’in tam karşısındaki nokta Gölge Aks’tır; sarı çizgi Güneş–Gölge Aks hattını gösterir.</li><li>Mor hattın uçlarında Yükselen ve Kök Aks bulunur. İnce bağlantılar her noktanın tam adını ve hesaplanan burcunu gösterir.</li><li>Ay çizgisi, gerçek konumuna ait içteki renkli yayda sonlanır; dış çember Güneş yolunu gösterir. Ay Duygu Ekseni seçeneğini açın. Ay’ın karşısındaki nokta, Karanlık Ay adıyla gösterilir. Ay ve Karanlık Ay Aksı, Ay Duygu Ekseni’nin iki ucudur.</li><li>Ay düğümlerini ayrıca açabilirsiniz. Bu noktalar, Ay yörüngesinin ekliptikle kesiştiği iki yöndür.</li></ol><p className="mt-4 text-xs text-slate-400">Bu çizim örnektir. Kişisel haritanız doğum bilgilerinize göre hesaplanır. Takımyıldızların genişlikleri eşit olmadığı için karşı ucu burç listesinden sayarak bulamazsınız.</p><Link href="/" className="mt-4 inline-block font-semibold text-cyan-200">Kendi haritamı hesapla →</Link></section></div>
 <div className="mt-6 space-y-4">{axes.map(axis=><article className="panel p-5 sm:p-7" key={axis.title}><h2 className="display text-2xl text-violet-100">{axis.title}</h2><p className="mt-2 font-semibold text-cyan-100">{axis.question}</p><p className="mt-3 text-slate-300">{axis.text}</p></article>)}</div>
 <section className="prose page-narrow mt-8"><h2>Ay düğümleri neden ayrı?</h2><p>Kuzey ve Güney Ay düğümleri, Ay’ın yörünge düzlemi ile Dünya’nın Güneş çevresindeki yörünge düzleminin kesişiminden hesaplanır. Ay’ın bulunduğu yönün karşıtı değildir. Sembolik okumada Güney düğüm alışılmış beceri ve tepkileri, Kuzey düğüm geliştirilecek yaklaşımı temsil eder. Bu iki nokta, Ay Duygu Ekseni ile aynı başlık altında eritilmez.</p><h2>Bir aks sonucu nasıl yorumlanır?</h2><p>Önce hattın iki ucundaki yerleşimleri okuyun. Sonra bu iki ihtiyacın yaşamınızda nerede karşılaştığını düşünün. Bir uç “iyi”, diğeri “kötü” değildir; her niteliğin işe yarayan ve aşırıya kaçan bir kullanımı vardır. Otomatik yorum, bu karşılaşmayı somut davranışlar ve uygulanabilir önerilerle anlatır. Başlangıç için bütün haritayı aynı anda çözmeye çalışmak yerine, hayatınızdaki tek bir ilişki veya durum üzerinden ilerleyin.</p><h2>Bu yaklaşımın sınırı nedir?</h2><p>Kök Aks, Gölge Aks ve Karanlık Ay adları RealHoroscope’un sembolik okuma çerçevesidir. Karanlık Ay burada Lilith, Ay apojesi veya yeniay anlamına gelmez. Noktaların konumları hesaplanır; bunlara verilen kişilik ve gelişim anlamları bilimsel bir kişilik testi değildir. Bu yorum belirli bir olayın yaşanacağını öngörmez.</p><p><Link href="/yontem">Hesaplama yöntemini incele →</Link> · <Link href="/burc-uyumu">İlişki karşılaştırmasına geç →</Link></p></section><AxisMethod/></div></main>;}
