import { FullLink as Link } from "@/components/full-link";
import { ArrowRight, BookOpen, CheckCircle2, Compass, Orbit } from "lucide-react";
import { BirthCalculator } from "@/components/birth-calculator";
import { ZodiacDiagram } from "@/components/zodiac-diagram";
import { articles } from "@/lib/articles";
import { zodiacSigns } from "@/lib/zodiac-data";

export default function Home() {
  return <main id="ana-icerik" className="page-main">
    <div className="site-shell">
      <header className="mb-8 max-w-4xl"><p className="eyebrow">Astronomik konum · Sembolik yorum</p><h1 className="display mt-3 text-4xl sm:text-6xl">Doğduğunuz andaki gerçek gökyüzünü görün.</h1><p className="lede mt-5">Güneş, Ay ve yükselen noktanızı sabit tarih tablosuyla değil; seçtiğiniz zaman, doğrulanan konum ve IAU takımyıldız bölgeleriyle hesaplayın.</p></header>
      <BirthCalculator />
      <section className="mt-12 grid gap-5 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div><p className="eyebrow">İki katman, açık ayrım</p><h2 className="display mt-3 text-3xl sm:text-5xl">Gökyüzü verisi ne söyler, yorum nerede başlar?</h2><p className="mt-5 text-slate-300">Bir gök cisminin koordinatı ve hangi takımyıldız bölgesinde bulunduğu astronomik olarak hesaplanabilir. Bu konumdan kişilik anlamı çıkarmak ise astrolojinin kültürel ve sembolik alanıdır. RealHoroscope bu iki cümleyi birbirine karıştırmaz.</p><div className="mt-6 grid gap-3"><div className="flex gap-3 rounded-xl border border-cyan-200/15 bg-cyan-300/5 p-4"><CheckCircle2 className="mt-1 shrink-0 text-cyan-200"/><div><strong>Astronomik katman</strong><p className="mt-1 text-sm text-slate-400">UTC zaman, enlem-boylam, efemeris koordinatı, IAU adı ve Ay fazı.</p></div></div><div className="flex gap-3 rounded-xl border border-violet-200/15 bg-violet-300/5 p-4"><BookOpen className="mt-1 shrink-0 text-violet-200"/><div><strong>Sembolik katman</strong><p className="mt-1 text-sm text-slate-400">Güneş, Ay, yükselen, Kök Aks ve Gölge Aks için açıkça etiketlenmiş yorum.</p></div></div></div><Link href="/yontem" className="mt-6 inline-flex items-center gap-2 font-bold text-violet-200">Yöntemi adım adım incele <ArrowRight size={17}/></Link></div><div className="panel p-4 sm:p-7"><ZodiacDiagram compact/></div></section>
      <section className="mt-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Ekliptik üzerindeki 13 bölge</p><h2 className="display mt-2 text-3xl sm:text-4xl">Takımyıldız kütüphanesi</h2></div><Link href="/burclar" className="inline-flex items-center gap-2 text-sm font-bold text-violet-200">Tümünü karşılaştır <ArrowRight size={16}/></Link></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{zodiacSigns.map((sign)=><Link href={`/burclar/${sign.slug}`} key={sign.slug} className="group rounded-2xl border border-white/10 bg-white/[.035] p-4 transition hover:-translate-y-1 hover:border-violet-300/35 hover:bg-white/[.06]"><span className="text-3xl" style={{color:sign.accent}}>{sign.glyph}</span><h3 className="display mt-3 text-xl">{sign.name}</h3><p className="text-xs text-slate-500">{sign.latin} · {sign.iau}</p><p className="mt-3 line-clamp-2 text-xs text-slate-400">{sign.dates}</p></Link>)}</div></section>
      <section className="mt-16"><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div className="panel p-6 sm:p-8"><Orbit className="text-cyan-200"/><p className="eyebrow mt-5">Her gün değişen gök</p><h2 className="display mt-3 text-3xl">Bugünün Güneş ve Ay konumu</h2><p className="mt-4 text-sm text-slate-300">Güncel takımyıldızları, Ay fazını ve yıl içindeki Güneş geçişlerini tek ekranda izleyin.</p><Link href="/gokyuzu" className="mt-6 inline-flex items-center gap-2 rounded-full bg-cyan-200 px-5 py-2.5 text-sm font-extrabold text-[#071016]">Bugünün göğünü aç <Compass size={17}/></Link></div><div><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Editörlü rehber</p><h2 className="display mt-2 text-3xl">Önce kavramı anlayın</h2></div><Link className="text-sm font-bold text-violet-200" href="/rehber">Tüm yazılar</Link></div><div className="grid gap-3 sm:grid-cols-2">{articles.slice(0,4).map(article=><Link key={article.slug} href={`/rehber/${article.slug}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 hover:border-violet-300/30"><p className="text-xs font-bold text-cyan-200/75">{article.category} · {article.readTime}</p><h3 className="mt-2 text-lg font-bold leading-snug">{article.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-400">{article.description}</p></Link>)}</div></div></div></section>
      <section className="mt-16 rounded-2xl border border-amber-200/15 bg-amber-200/[.035] p-6 sm:p-8"><div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow !text-amber-200">Şeffaflık notu</p><h2 className="display mt-2 text-2xl">“Gerçek” sözcüğü gökyüzü konumunu anlatır.</h2><p className="mt-3 max-w-3xl text-sm text-slate-300">Platformun astronomik hesabı gök cisminin gerçek yönünü ifade eder. Astrolojik kişilik açıklamalarının bilimsel öngörü gücüne sahip olduğu iddia edilmez. Kaynak, sürüm ve sınırlamalar açıkça yayımlanır.</p></div><Link href="/editor-ilkeleri" className="inline-flex items-center gap-2 whitespace-nowrap font-bold text-amber-100">Editör ilkeleri <ArrowRight size={17}/></Link></div></section>
    </div>
  </main>;
}
