"use client";
import { useCallback,useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
type Item={id:number;name:string;email?:string;subject?:string;message:string;status:string;created_at:string};
const statuses:Record<string,string>={new:'Yeni',reviewed:'İncelendi',closed:'Kapatıldı',pending:'Onay bekliyor',approved:'Yayında',rejected:'Yayınlanmadı'};
export function AdminInbox(){
 const[kind,setKind]=useState<'messages'|'comments'>('messages'),[items,setItems]=useState<Item[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(before?:number)=>{setBusy(true);setError('');try{const response=await fetch(`/api/admin?kind=${kind}${before?'&before='+before:''}`,{cache:'no-store'});const data=await response.json() as {error?:string;items:Item[];next:number|null};if(!response.ok)throw Error(data.error??"İşlem tamamlanamadı.");setItems(old=>before?[...old,...data.items]:data.items);setNext(data.next);}catch(e){setError(e instanceof Error?e.message:'Kayıtlar yüklenemedi.');}finally{setBusy(false);}},[kind]);
 useEffect(()=>{setItems([]);setNext(null);void load();},[load]);
 async function update(id:number,status:string){setBusy(true);setError('');try{const response=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id,status})});const data=await response.json() as {error?:string;items:Item[];next:number|null};if(!response.ok)throw Error(data.error??"İşlem tamamlanamadı.");setItems(old=>old.map(item=>item.id===id?{...item,status}:item));}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await fetch('/api/admin/session',{method:'DELETE'});window.location.reload();}finally{setBusy(false);}}
 return <section className="mt-6"><div className="flex flex-wrap gap-2"><Button disabled={busy} variant={kind==='messages'?'default':'outline'} onClick={()=>setKind('messages')}>İletişim mesajları</Button><Button disabled={busy} variant={kind==='comments'?'default':'outline'} onClick={()=>setKind('comments')}>Topluluk yorumları</Button><Button disabled={busy} variant="outline" onClick={()=>void load()}>Yenile</Button><Button disabled={busy} variant="outline" onClick={()=>void logout()}>Çıkış yap</Button></div><p role="status" className="mt-3 text-sm text-cyan-100">{busy?'Yükleniyor…':error}</p>{!busy&&!error&&!items.length&&<p className="mt-4 text-slate-400">Henüz kayıt yok.</p>}<div className="mt-4 space-y-4">{items.map(item=><article key={item.id} className="panel p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">{item.name}{item.subject?' · '+item.subject:''}</h2><span className="text-sm text-cyan-100">{statuses[item.status]}</span></div><p className="mt-2 text-xs text-slate-400">{new Date(item.created_at).toLocaleString('tr-TR')}</p><p className="my-4 whitespace-pre-wrap break-words text-slate-200">{item.message}</p>{item.email&&<a href={`mailto:${encodeURIComponent(item.email)}?subject=${encodeURIComponent('Re: '+(item.subject??''))}`} className="text-sm text-violet-200 underline">E-postayla yanıtla · {item.email}</a>}<div className="mt-4 flex flex-wrap gap-2">{(kind==='comments'?['approved','rejected','pending']:['reviewed','closed','new']).map(status=><Button key={status} size="sm" variant="outline" disabled={busy||item.status===status} onClick={()=>void update(item.id,status)}>{statuses[status]}</Button>)}</div></article>)}</div>{next&&<Button disabled={busy} className="mt-5" onClick={()=>void load(next)}>Önceki kayıtları yükle</Button>}</section>;
}
