"use client";
import { useEffect, useState } from 'react';
import { cities, type BirthInput } from '@/lib/birth-input';
const field='w-full rounded-xl border border-white/15 bg-[#0b0d1b] p-3 text-sm text-slate-100';
type Geo={lat:number;lon:number;label:string;zone?:string};
export function BirthFields({value,onChange}:{value:BirthInput;onChange:(v:BirthInput)=>void}) {
  const [zones,setZones]=useState<string[]>([]); const [rows,setRows]=useState<Geo[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [zoneQuery,setZoneQuery]=useState('');
  useEffect(()=>{setZones(Intl.supportedValuesOf('timeZone'));},[]);
  const change=(patch:Partial<BirthInput>)=>onChange({...value,...patch});
  const filteredZones=zones.filter(zone=>!zoneQuery.trim()||zone.replaceAll('_',' ').toLocaleLowerCase('tr-TR').includes(zoneQuery.trim().toLocaleLowerCase('tr-TR')));
  const visibleZones=value.zone&&!filteredZones.includes(value.zone)?[value.zone,...filteredZones]:filteredZones;
  async function search(){setBusy(true);setError('');setRows([]);try{const response=await fetch(`/api/geocode?city=${encodeURIComponent(value.city)}&country=${encodeURIComponent(value.country)}&candidates=1`);const data=await response.json() as Geo & {results?:Geo[];error?:string};if(!response.ok)throw new Error(data.error);const results=data.results??[data];if(!results.length)throw new Error('Konum bulunamadı. Şehir ve ülke adını kontrol edin.');setRows(results);}catch(e){setError(e instanceof Error?e.message:'Şehir bulunamadı. Koordinatları elle girebilirsiniz.');}finally{setBusy(false);}}
  return <div className="grid gap-3">
    <label className="grid gap-1.5 text-sm font-semibold">Doğum tarihi ve yerel saat<input className={field} type="datetime-local" min="1900-01-01T00:00" max="2100-12-31T23:59" required value={value.date} onInput={e=>change({date:e.currentTarget.value})} onChange={e=>change({date:e.target.value})}/></label>
    <label className="grid gap-1.5 text-sm font-semibold">Doğum yeri<select className={field} value={value.mode} onChange={e=>{setRows([]);change({mode:e.target.value as BirthInput['mode'],city:e.target.value==='tr'?'34':'',zone:e.target.value==='tr'?'Europe/Istanbul':'',lat:'',lon:'',label:''});}}><option value="tr">Türkiye</option><option value="world">Türkiye dışında / koordinat gir</option></select></label>
    {value.mode==='tr'?<><label className="grid gap-1.5 text-sm font-semibold">İl<select className={field} value={value.city} onChange={e=>change({city:e.target.value})}>{cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="text-xs text-slate-400">İl merkezi koordinatları kullanılır. Kesin doğum konumu için koordinat girişini seçebilirsiniz. Tarihe ait Türkiye saat kuralları uygulanır.</p></>:<>
      <div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-sm">Şehir<input className={field} value={value.city} maxLength={80} onChange={e=>{setRows([]);setZoneQuery('');change({city:e.target.value,lat:'',lon:'',label:'',zone:''});}}/></label><label className="grid gap-1 text-sm">Ülke<input className={field} value={value.country} maxLength={80} onChange={e=>{setRows([]);setZoneQuery('');change({country:e.target.value,lat:'',lon:'',label:'',zone:''});}}/></label></div>
      <button className="rounded-xl border border-cyan-200/20 bg-cyan-200/5 p-2 text-sm text-cyan-100 disabled:opacity-40" type="button" disabled={busy||!value.city.trim()||!value.country.trim()} onClick={search}>{busy?'Aranıyor…':'Şehri bul'}</button>
      {error&&<p role="alert" className="text-xs text-rose-200">{error} Koordinatları elle girebilirsiniz.</p>}
      {rows.length>0&&<label className="grid gap-1 text-sm">Doğru konumu seçin<select className={field} value={value.label} onChange={e=>{const row=rows.find(r=>r.label===e.target.value);if(row){change({lat:String(row.lat),lon:String(row.lon),label:row.label,zone:row.zone??value.zone});if(row.zone)setZoneQuery(row.zone.split('/').at(-1)?.replaceAll('_',' ')??'');}}}><option value="">Konum seçin</option>{rows.map(r=><option key={`${r.lat},${r.lon}`} value={r.label}>{r.label}</option>)}</select></label>}
      <div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-sm">Enlem<input className={field} type="number" step="any" min="-89.9999" max="89.9999" required value={value.lat} placeholder="48.8566" onChange={e=>change({lat:e.target.value,label:''})}/></label><label className="grid gap-1 text-sm">Boylam<input className={field} type="number" step="any" min="-180" max="180" required value={value.lon} placeholder="2.3522" onChange={e=>change({lon:e.target.value,label:''})}/></label></div>
      <p className="text-xs text-slate-400">Saat dilimini doğum yerine göre seçin; yaşadığınız yere göre değil. Arama yalnızca şehir ve ülkeyi OpenStreetMap’e gönderir. Doğum bilgileri cihazınızda hesaplanır.</p>
    </>}
    {value.mode==='world'&&<label className="grid gap-1.5 text-sm font-semibold">Saat diliminde ara<input className={field} value={zoneQuery} placeholder="Örn. Paris, New York, Tokyo" onChange={e=>setZoneQuery(e.target.value)}/><span className="text-xs font-normal text-slate-400">Doğum şehrinizin bölge adını yazın; aşağıdaki liste eşleşen seçenekleri gösterecektir.</span></label>}
    <label className="grid gap-1.5 text-sm font-semibold">Doğum yerinin saat dilimi<select className={field} required value={value.zone} onChange={e=>change({zone:e.target.value})}><option value="">Saat dilimi seçin</option><option value="Europe/Istanbul">Türkiye — İstanbul</option>{visibleZones.filter(z=>z!=='Europe/Istanbul').map(z=><option key={z} value={z}>{z.replaceAll('_',' ')}</option>)}<optgroup label="Doğum kaydında UTC farkı belirtilmişse">{Array.from({length:105},(_,i)=>{const minutes=i*15-720,sign=minutes<0?'-':'+';const zone=`UTC${sign}${String(Math.floor(Math.abs(minutes)/60)).padStart(2,'0')}:${String(Math.abs(minutes)%60).padStart(2,'0')}`;return <option key={zone} value={zone}>{zone} · sabit fark</option>;})}</optgroup></select><span className="text-xs font-normal text-slate-400">Şehir saat dilimleri, doğum tarihinizdeki yaz/kış saati kurallarını otomatik uygular. Sabit UTC farkını yalnız doğum kaydınızda açıkça yazıyorsa seçin.</span></label>
  </div>;
}
