"use client";
import { useMemo,useState } from 'react';
import { zodiacSigns } from '@/lib/zodiac-data';
import { pairReading,compatibilityReading,type Reading } from '@/lib/interpretations';
import { initialBirth,resolveBirth } from '@/lib/birth-input';
import { BirthFields } from './birth-fields';
import { ReadingCards } from './combination-reading';
export function CompatibilityCalculator(){
 const [mode,setMode]=useState<'quick'|'birth'>('quick'),[first,setFirst]=useState('Ari'),[second,setSecond]=useState('Lib');
 const [a,setA]=useState(initialBirth),[b,setB]=useState(initialBirth),[readings,setReadings]=useState<Reading[]|null>(null),[error,setError]=useState(''),[record,setRecord]=useState('');
 const quick=useMemo(()=>pairReading(first,second),[first,second]);
 function calculate(e:React.FormEvent){e.preventDefault();setError('');setReadings(null);try{let ra,rb;try{ra=resolveBirth(a);}catch(e){throw new Error(`Birinci kişi: ${e instanceof Error?e.message:''}`);}try{rb=resolveBirth(b);}catch(e){throw new Error(`İkinci kişi: ${e instanceof Error?e.message:''}`);}setReadings(compatibilityReading(ra.result,rb.result));setRecord(`1: ${ra.label} · ${ra.result.utc} | 2: ${rb.label} · ${rb.result.utc}`);}catch(e){setError(e instanceof Error?e.message:'Hesaplama tamamlanamadı.');}}
 const picks=[{value:first,set:setFirst,label:'Birinci takımyıldız'},{value:second,set:setSecond,label:'İkinci takımyıldız'}];
 return <div className="panel p-5 sm:p-7"><div className="mb-5 flex flex-wrap gap-2" role="group" aria-label="Karşılaştırma biçimi">{([['quick','Hızlı eşleşme'],['birth','Doğum bilgileriyle uyum']] as const).map(([key,label])=><button type="button" key={key} aria-pressed={mode===key} onClick={()=>setMode(key)} className={`rounded-full border px-4 py-2 text-sm ${mode===key?'border-violet-300/40 bg-violet-300/15 text-violet-100':'border-white/10 text-slate-400'}`}>{label}</button>)}</div>
 {mode==='quick'?<><p className="mb-4 text-sm text-slate-400">13 takımyıldızın tüm ikili eşleşmeleri için ortak yönler, zorlanmalar ve konuşma önerileri.</p><div className="grid gap-3 sm:grid-cols-2">{picks.map(p=><label key={p.label} className="grid gap-2 text-sm">{p.label}<select className="rounded-xl border border-white/15 bg-[#0b0d1b] p-3" value={p.value} onChange={e=>p.set(e.target.value)}>{zodiacSigns.map(s=><option key={s.iau} value={s.iau}>{s.glyph} {s.name}</option>)}</select></label>)}</div><ReadingCards readings={[quick]}/></>:<><form onSubmit={calculate}><div className="grid gap-6 lg:grid-cols-2"><fieldset><legend className="mb-3 text-lg text-violet-200">Birinci kişi</legend><BirthFields value={a} onChange={v=>{setA(v);setReadings(null);}}/></fieldset><fieldset><legend className="mb-3 text-lg text-cyan-200">İkinci kişi</legend><BirthFields value={b} onChange={v=>{setB(v);setReadings(null);}}/></fieldset></div>{error&&<p role="alert" className="mt-4 text-sm text-rose-200">{error}</p>}<button className="mt-5 rounded-xl bg-violet-300 px-6 py-3 font-semibold text-[#160b24]" type="submit">Birlikte yorumla</button></form>{readings&&<section className="mt-6" aria-live="polite"><h2 className="display text-3xl">İki haritanın buluşması</h2><p className="mt-2 text-xs text-slate-400">Sıralama birinci kişi → ikinci kişi şeklindedir. Karşılaştırma yerleşim temalarını kullanır; gezegenler arası açılara dayanan tam sinastri hesabı değildir.</p><ReadingCards readings={readings}/><details className="mt-4 text-xs text-slate-400"><summary className="cursor-pointer">Hesaplama kaydı</summary><p className="mt-2 break-words">{record}</p></details></section>}</>}
 <p className="mt-5 text-xs text-slate-400">Yorumlar düzenlenmiş sembolik profiller ve birleşim kurallarıyla otomatik oluşur. Uyum yüzdesi veya ilişki geleceği ölçülmez. Doğum bilgileri cihazınızdan gönderilmez.</p></div>;
}
