import type { GuideArticle } from './articles';

// Original editorial guides. Internal method links describe our own interpretation,
// not external scientific endorsement of personality claims.
const method = { title: 'RealHoroscope: hesap ve yorum yöntemi', url: '/yontem' };
const axes = { title: 'RealHoroscope: aks tanımları', url: '/gorsel-aks' };
const engine = { title: 'Astronomy Engine: kullanılan hesaplama fonksiyonları', url: 'https://github.com/cosinekitty/astronomy/blob/master/source/js/README.md' };
const zones = { title: 'IANA: tarihsel saat dilimi veritabanı', url: 'https://www.iana.org/time-zones' };
const iau = { title: 'IAU: takımyıldız bölgeleri', url: 'https://iauarchive.eso.org/public/themes/constellations/' };

type Draft = Omit<GuideArticle, 'readTime' | 'updated'>;
const drafts: Draft[] = [
  {
    slug: 'kok-aks-sakli-potansiyel', title: 'Kök Aks: İçinizde taşıdığınız potansiyeli nasıl okuyabilirsiniz?',
    description: 'Kök Aks’ı eksiklik veya geçmişe mahkûmiyet olarak değil, mevcut fakat yeterince kullanılmayan yeteneklerin dili olarak ele alın.',
    category: 'Akslar', sources: [axes, method], related: ['gunes-kok-aks-ayni-burc', 'kok-aks-ve-ay-dugumleri'],
    sections: [
      { heading: 'Saklı olması, sizde bulunmadığı anlamına gelmez', paragraphs: ['Kök Aks, RealHoroscope yorumunda bugün içinizde bulunan fakat henüz yeterince fark etmediğiniz potansiyeli anlatır. Bir becerinin görünür olmaması, onun hiç gelişmediği anlamına gelmez. Kimi yetenekler çok doğal geldiği için küçümsenir; kimileri kullanılmadığı, desteklenmediği veya başka sorumlulukların gerisinde kaldığı için sessizleşir. Buradaki okuma, kişiye dışarıdan yeni bir kimlik eklemekten çok, kendi birikimiyle yeniden ilişki kurmasını amaçlar.', 'Bu nedenle “Kök Aks’ım şu burç; bende o özellik yok” düşüncesini hemen bir çelişki saymayın. Yorumun sorusu, o özelliği sürekli sergileyip sergilemediğiniz değil, gerektiğinde hangi niteliğe erişebildiğinizdir. Potansiyel ile alışkanlık aynı şey değildir. Birinde açılabilecek bir kapasite, diğerinde sık tekrarlanan bir kullanım biçimi vardır.'] },
      { heading: 'Geçmiş deneyim ile mevcut güç arasındaki bağ', paragraphs: ['Geçmiş deneyimlerden edinilen beceriler, bugün hâlâ kullanılabilir bir birikim oluşturur. Sabır, anlatma, ayırt etme veya yön bulma gibi nitelikler yalnız başarılarla değil, zorlanmalarla da gelişebilir. Kök Aks yorumunda geçmişe bakmanın amacı orada kalmak değildir. Önemli olan, yaşananlardan elde edilen hangi kapasitenin bugünkü yaşamda daha bilinçli kullanılabileceğini görmektir.'] },
      { heading: 'Yükselenden farkı', paragraphs: ['Yükselen dış dünyaya yaklaşımınızı anlatırken Kök Aks, bu görünür tavrın gerisinde değerlendirebileceğiniz bir kaynağı temsil eder. İki nokta hesapta karşıt yönlerdedir; fakat yorumda birbirinin düşmanı değildir. Hızlı görünen birinin yavaş ve özenli çalışma kapasitesi bulunabilir. Sessiz görünen birinin anlatıcı tarafı güçlü olabilir. Haritanın amacı tek bir sıfatla kişiyi kapatmak değil, görünen ile henüz kullanılmayan arasındaki ilişkiyi araştırmaktır.'] },
      { heading: 'Reenkarnasyon dilini nasıl ele alıyoruz?', paragraphs: ['Bazı spiritüel okumalar kökteki birikimi geçmiş yaşam benzetmesiyle anlatır. RealHoroscope bir hesaplamadan geçmiş yaşam bilgisi çıkarmaz ve reenkarnasyonu doğruladığını iddia etmez. Bu benzetme tercih edilse bile yorumun uygulanabilir merkezi bugündür: hangi beceriyi tanıyorsunuz, hangisini değersiz sayıyorsunuz ve hangisini geliştirmek istiyorsunuz? Kök Aks, kesin bir yaşam öyküsü değil, mevcut potansiyel üzerine düşünmek için kullanılan bir yorum alanıdır.'] },
    ],
  },
  {
    slug: 'gunes-kok-aks-ayni-burc', title: 'Güneş ve Kök Aks aynı burçtaysa ne anlama gelir?',
    description: 'Aynı burcun iki farklı görevde görünmesi neden çelişki değildir? Kimlik, saklı yetenek ve bilinçli kullanım arasındaki ilişki.',
    category: 'Akslar', sources: [axes, method], related: ['kok-aks-sakli-potansiyel', 'ayni-burc-farkli-yerlesimler'],
    sections: [
      { heading: 'Aynı ad, aynı görev demek değildir', paragraphs: ['Güneş ile Kök Aks’ın aynı burçta çıkması, yorumun aynı cümleyi iki kez söylemesini gerektirmez. Güneş, kendinizi hangi nitelikler üzerinden tanımladığınızı ve yaşam yönünüzü anlatır. Kök Aks ise bu niteliklerin içinde taşıdığınız, henüz yeterince işlemediğiniz kapasiteyi vurgular. Bir özelliği kendinize yakıştırmak, o özelliği her durumda bilinçli ve verimli kullanabildiğiniz anlamına gelmez.', 'Buradaki gelişim teması başka biri olmak değil, tanıdığınız tarafınızın daha derin bir kullanımını öğrenmektir. Kendi gücünüzü sürekli ispatlamaya çalışmak yerine, onu hangi amaç için ve hangi ölçüde kullanacağınızı seçmeniz önem kazanır. Tekrar, tamamlanmış bir ustalık belgesi değil; üzerinde çalışılabilecek belirgin bir odaktır.'] },
      { heading: 'Başak örneği: dikkat ile ustalık arasındaki fark', paragraphs: ['Güneş ve Kök Aks Başak olduğunda kişi ayrıntıları fark eden yönünü kolayca tanıyabilir. Saklı potansiyel ise yalnız kusur bulmak değil, karmaşık bir işi uygulanabilir düzene çevirebilmektir. Dikkat sürekli kişinin kendisini eleştirmesine harcanıyorsa yetenek vardır ama kullanım alanı daralmıştır. Yorumu güçlendiren soru “Ne kadar titizim?” değil, “Bu dikkati hangi yararlı işe dönüştürüyorum?” olur.'] },
      { heading: 'Aslan ve Balık örneklerinde değişen vurgu', paragraphs: ['Aslan tekrarında görünür olma isteği ile yaratıcı üretimi sahiplenme cesareti ayrılır. Takdir beklemek, üretme gücünün bütünü değildir; kendi ifadesine değer vermek potansiyeli açar. Balık tekrarında ise duyarlılık ile duyarlılığı anlamlı bir biçime dönüştürmek ayrılır. Çok şey hissetmek, hissedilen her şeyi taşımak zorunda olmak demek değildir. Sınır ve ifade alanı, yaratıcı kapasitenin kullanılmasını kolaylaştırır.'] },
      { heading: 'Hesap açısından bu sonuç mümkün mü?', paragraphs: ['Kök Aks yükselenin karşısından, Güneş ise kendi gökyüzü konumundan hesaplanır. Güneş’in Kök Aks’la aynı bölgede olması bu tanımlara aykırı değildir. Aynı takımyıldız adı, noktaların tam aynı derecede bulunduğunu da göstermez. Bu nedenle yalnız isim eşleşmesine bakıp tam kavuşum, özel kader veya kesin üstünlük sonucu çıkarılmaz. Yorumda ortak tema ele alınır; geometri ayrıca korunur.'] },
    ],
  },
  {
    slug: 'golge-aks-karsit-nitelikler', title: 'Gölge Aks: Karşıt niteliği bastırmadan denge kurmak',
    description: 'Güneş’in karşıt noktası neden bir düşman ya da kötü özellik değildir? Gölge Aks’ın kimlik yorumundaki yerini öğrenin.',
    category: 'Akslar', sources: [axes, method], related: ['karanlik-ay-duygu-ekseni', 'gunes-kok-aks-ayni-burc'],
    sections: [
      { heading: 'Gölge sözcüğünün taşıdığı yanlış beklenti', paragraphs: ['Gölge Aks’ı kötü yan, uğursuzluk veya saklanması gereken bir kusur gibi okumak yorumun amacını değiştirir. RealHoroscope’ta bu ad, Güneş’in tam karşısındaki yön için kullanılır. Yorum bakımından kendinize kolayca yakıştıramadığınız, bazen başkalarında görünce güçlü tepki verdiğiniz nitelikleri ele alır. Bir niteliği kabul etmek, onun ölçüsüz veya zarar veren kullanımını onaylamak değildir.', 'Örneğin kararlılığı değerli bulmak, esnekliği zayıflık saymayı gerektirmez. Aynı şekilde uzlaşmayı önemsemek, kişisel sınırdan vazgeçmek anlamına gelmez. Gölge okuması, kimliğinizi korurken hangi karşıt kapasiteye de ihtiyaç duyduğunuzu araştırır. Böylece bir özellik tek mümkün davranış olmaktan çıkar.'] },
      { heading: 'Karşıtlık ile tamamlayıcılığı ayırmak', paragraphs: ['Karşıt noktalar çizimde birbirinden uzaktır; psikolojik yorumda ise birlikte kullanılabilir niteliklere dönüştürülebilir. Bu, her karşıt insanla anlaşacağınız anlamına gelmez. Uyumsuz davranışları “Benim gölgem” diyerek kabullenmek zorunda değilsiniz. Yararlı ayrım, davranışın zarar veren biçimi ile arkasındaki meşru ihtiyacı birbirinden ayırmaktır. Sınır koyma ihtiyacını tanımak, kabalığı kabul etmek değildir.'] },
      { heading: 'Kök Aks ile neden karışmamalı?', paragraphs: ['Kök Aks mevcut potansiyelinizi kullanma temasını taşır. Gölge Aks ise bilinçli kimliğinizin dışarıda bıraktığı niteliğe yer açmayı anlatır. İki bölümde benzer bir beceriden söz edilse bile soru farklıdır: Kök Aks “Bende zaten bulunan neyi kullanmıyorum?” diye sorar; Gölge Aks “Hangi ihtiyacı kendime yakıştıramıyorum?” sorusunu açar. Bu fark, yorumun aynı sözcüklerle tekrarlanmasını önler.'] },
      { heading: 'Sonucu okurken korunacak ölçü', paragraphs: ['Önce Güneş bölümünde sahiplendiğiniz temayı, sonra Gölge Aks bölümündeki karşıt ihtiyacı okuyun. Her ikisinin de yararlı ve aşırıya kaçan kullanımını düşünün. Amaç Güneş burcunuzu bırakmak ya da karşıt burca dönüşmek değildir. Davranış seçeneklerini genişletmek, bir tepkinin her durumda doğru sayılmasını engeller. Bu çerçeve ilişki veya sağlık hakkında teşhis koymaz; kişinin kendi seçimlerini incelemesi için bir yorum sunar.'] },
    ],
  },
  {
    slug: 'karanlik-ay-duygu-ekseni', title: 'Ay Duygu Ekseni: Karanlık Ay hangi yüzleşmeyi anlatır?',
    description: 'Ay’ın güven ihtiyacı ile Karanlık Ay’ın karşıt teması nasıl birlikte okunur? Lilith ve Ay düğümlerinden farkları.',
    category: 'Akslar', sources: [axes, method], related: ['golge-aks-karsit-nitelikler', 'kok-aks-ve-ay-dugumleri'],
    sections: [
      { heading: 'Duygu ile duyguyu koruma biçimi', paragraphs: ['Ay yorumu, güven duyduğunuz koşulları ve kendiliğinden verdiğiniz duygusal tepkileri ele alır. Karanlık Ay Aksı ise bu tanıdık düzenin karşıt niteliğiyle yüzleşme temasını taşır. İki noktayı birleştiren hat Ay Duygu Ekseni’dir. Ay’ın ihtiyacı yanlış değildir; fakat tek güven yolu hâline geldiğinde farklı bir ihtiyacı duymayı zorlaştırabilir. Karşıt uç bu daralmayı düşünmek için kullanılır.', 'Buradaki sınav sözcüğü yaklaşan bir felaket, ceza veya kaçınılmaz olay anlamına gelmez. Yorumun odağı, zorlandığınızda hangi karşıt kapasiteyi kullanmayı öğrenebileceğinizdir. Duygusal ihtiyaçlarınızı reddetmek değil, onları ifade ederken daha geniş bir hareket alanı bulmak amaçlanır.'] },
      { heading: 'Karşıt ihtiyaç neden rahatsız edici gelebilir?', paragraphs: ['Yakınlık üzerinden güven arayan biri için mesafe hemen ilgisizlik gibi görünebilir. Özerkliğe önem veren biri ise yakınlık isteğini sınırlanma gibi okuyabilir. Bu örnekler kişiye tanı koymaz; aynı ihtiyacın farklı yorumlanabileceğini gösterir. Karanlık Ay okumasında karşıt tema, alışılmış tepkinizin otomatik olarak tek açıklama sayılmasını sorgulatır. Karşıdakinin niyetini burcundan çıkarmak yerine açık iletişim kurmak her zaman önemlidir.'] },
      { heading: 'Lilith, yeniay ve düğümlerden farklıdır', paragraphs: ['Bu platformdaki Karanlık Ay Aksı, Ay’ın gökyüzü yönünün karşıt noktasıdır. Lilith adıyla kullanılan Ay apojesi hesabı değildir. Ay’ın görünür aydınlık kısmını anlatan yeniay evresi de değildir. Kuzey ve Güney Ay düğümleri ise yörünge düzlemlerinin kesişimine dayanır. Adlarında Ay geçmesi, bu kavramların aynı noktayı veya aynı yorumu taşıdığı anlamına gelmez.'] },
      { heading: 'Birleştirerek okuma', paragraphs: ['Ay bölümünden güven ihtiyacını, Karanlık Ay bölümünden dengeye çağrılan niteliği seçin. Sonra bunları “Birine sahipsem diğerini kaybederim” düşüncesine sıkıştırmadan değerlendirin. Yakınlık ve sınır, duyarlılık ve açıklık, süreklilik ve değişim birlikte var olabilir. Yorumun değeri karşıt tarafı yüceltmesinde değil, ihtiyaçların birbirini bütünüyle dışlamadığını göstermesindedir. Duygusal güçlükler sürüyorsa astrolojik metin profesyonel desteğin yerine geçmez.'] },
    ],
  },
  {
    slug: 'kok-aks-ve-ay-dugumleri', title: 'Kök Aks ile Ay düğümleri neden aynı şey değildir?',
    description: 'Saklı potansiyel, alışılmış tepki ve gelişim yönünü birbirine karıştırmadan okumak için üç ayrı soru.',
    category: 'Akslar', sources: [axes, method], related: ['kok-aks-sakli-potansiyel', 'karanlik-ay-duygu-ekseni'],
    sections: [
      { heading: 'Benzer kelimeler, farklı roller', paragraphs: ['Kök Aks ve Güney Ay düğümü açıklamalarında birikim, tanıdıklık veya yetenek gibi sözcüklerle karşılaşabilirsiniz. Bu benzerlik iki bölümün aynı olduğu anlamına gelmez. RealHoroscope’ta Kök Aks, mevcut fakat tam kullanılmayan potansiyele odaklanır. Güney düğüm, yorum geleneğinde tanıdık beceriler ve alışılmış tepkilerle ele alınır. Kuzey düğüm ise geliştirilecek yaklaşımın simgesidir. Üçüne aynı “geçmiş” etiketini vermek bu ayrımı siler.'] },
      { heading: 'Üç soruyla okuma düzeni', paragraphs: ['Kök Aks için “Bende bulunduğu hâlde hangi kapasiteyi küçümsüyorum?” sorusunu sorun. Güney düğümde “Hangi tepkiyi kolay ve tanıdık olduğu için tekrar ediyorum?” sorusu daha uygundur. Kuzey düğümde ise “Hangi yaklaşımı öğrenmek davranış alanımı genişletir?” sorusuna geçilir. Sorular farklı olduğunda benzer burç adları da metni birbirinin kopyası hâline getirmez.', 'Bir yeteneği kullanmakla aynı alışkanlığa sığınmak arasında önemli fark vardır. Düzen kurma becerisi üretken olabilir; belirsizliğe hiç izin vermeyen kontrol ise aynı niteliğin daralmış kullanımıdır. Yorum, beceriyi terk etmeyi değil, kullanım biçimini seçmeyi vurgular.'] },
      { heading: 'Hesaplama dayanakları ayrıdır', paragraphs: ['Kök Aks yükselen noktasının karşısından türetilir ve doğum yeri ile saate bağlı ufuk geometrisini izler. Ay düğümleri, Ay yörüngesi ile ekliptik düzleminin kesişim doğrultularıdır. Bu nedenle doğum yeri değiştiğinde aynı UTC anındaki düğümler ve Kök Aks aynı biçimde davranmaz. Aynı adların görünmesi, hesapların birleştirildiğini göstermez; ayrı noktalar aynı gökyüzü bölgesine düşebilir.'] },
      { heading: 'Geçmiş yaşam iddialarına mesafe', paragraphs: ['Düğümler bazı astroloji ekollerinde karmik bir dille yorumlanır. Bu dil, kişinin geçmiş yaşamını ölçen astronomik bir kayıt değildir. Harita bir suç, borç veya zorunlu kader kanıtı olarak kullanılamaz. RealHoroscope’un bu ayrımı koruması, yorumu değersizleştirmek için değil, neyin hesap neyin anlamlandırma olduğunu açık tutmak içindir. Potansiyelinizi keşfetmek için doğrulanamayan bir yaşam öyküsünü gerçek kabul etmeniz gerekmez.'] },
    ],
  },
  {
    slug: 'ayni-burc-farkli-yerlesimler', title: 'Güneş, Ay ve yükselen aynıysa yorum neden farklı olmalı?',
    description: 'Haritadaki tekrarları tek bir kişilik etiketine indirmeden; amaç, ihtiyaç ve dış tavır olarak ayrı okuyun.',
    category: 'Yorumlama', sources: [method], related: ['gunes-kok-aks-ayni-burc', 'sonucumu-nasil-okurum'],
    sections: [
      { heading: 'Burç adı tema, yerleşim görevdir', paragraphs: ['Bir burç adı farklı kartlarda tekrarlandığında yalnız nitelik yoğunlaşmaz; aynı niteliğin farklı işlevleri de ortaya çıkar. Güneş yorumu yöneldiğiniz amacı, Ay yorumu güven ihtiyacını, yükselen yorumu dış dünyaya yaklaşımınızı ele alır. Üç kartta aynı sıfatı sıralamak, bu işlevleri görünmez kılar. Tutarlı bir okumada tema korunur, fakat her kartın sorusu ve gelişim önerisi değişir.', 'Örneğin aynı burçta Güneş ve Ay bulunması, istek ile duygusal refleks arasında benzerlik olarak yorumlanabilir. Bu benzerlik her kararın doğru olduğunu göstermez; kişi bir tercihe hızla duygusal yatırım yapabilir. Ortak tema hem destekleyici tarafıyla hem de tek bakışa sıkışma olasılığıyla ele alınmalıdır.'] },
      { heading: 'Boğa temasını üç görevde düşünmek', paragraphs: ['Boğa Güneş yorumunda kalıcı değer oluşturma amacı öne çıkabilir. Boğa Ay yorumunda güvenilirlik ve devamlılık ihtiyacı ele alınır. Boğa yükselende ise yeni bir duruma ölçerek ve temkinli yaklaşma üslubu konuşulur. Bunlar birbirine bağlıdır ama aynı cümle değildir. Amaç üretmek, ihtiyaç güven duymak, yaklaşım ise acele etmeden değerlendirmek olabilir. Bu ayrım kişiyi tek kelimelik bir kalıba hapsetmez.'] },
      { heading: 'Öneriler neden birbirinin kopyası olmamalı?', paragraphs: ['Güneş için verilen bir öneri kişinin hedef seçimine yardımcı olabilir. Ay için olanı duygusal ihtiyacın fark edilmesine, yükselen için olanı ilk tepkideki iletişime odaklanmalıdır. Hepsinin altında “Daha açık konuşun” yazması, farklı görevleri aynı soruna indirger. Önerinin başarısı ne kadar iddialı göründüğüyle değil, ilgili yerleşimin sorusuna ne kadar açık cevap verdiğiyle değerlendirilir.'] },
      { heading: 'Tekrar kişiliğin tamamı değildir', paragraphs: ['Birden çok yerleşimin aynı bölgede olması, insanın yalnız o profile uyacağı anlamına gelmez. Deneyimler, çevre, ilişkiler ve bilinçli tercihler kişinin davranışını etkiler. Ayrıca aynı bölge adı, gök cisimlerinin tam aynı açıda bulunduğunu söylemez. Bu yüzden yalnız isim tekrarından özel güç, üstünlük veya tam kavuşum sonucu çıkarılmaz. Kök Aks tekrarında da mesele özelliğin zaten tamamlanmış olması değil, içeride taşınan kapasitenin bilinçli kullanımıdır.'] },
    ],
  },
  {
    slug: 'uyum-sonucunu-yuzdeye-indirmemek', title: 'Burç uyumunu tek bir yüzdeye indirmeden nasıl okuyabilirsiniz?',
    description: 'Ortak yön, duygusal ihtiyaç ve iletişim üslubu üzerinden ilişki karşılaştırmasını daha anlamlı kullanın.',
    category: 'İlişkiler', sources: [method], related: ['ayni-burc-farkli-yerlesimler', 'golge-aks-karsit-nitelikler'],
    sections: [
      { heading: 'Bir puanın sakladığı ayrıntı', paragraphs: ['İki kişi için tek bir uyum yüzdesi görmek kolaydır; fakat böyle bir sayı hangi ihtiyacın nasıl karşılandığını söylemez. Ortak hedefleri olan iki kişi duygularını farklı biçimde ifade edebilir. Benzer duygusal beklentilere sahip kişiler ise karar temposunda ayrışabilir. Bir ilişkinin niteliği yalnız burç adlarından ölçülmüş bir sonuç gibi sunulamaz. Bu nedenle karşılaştırmada farklı katmanları ayrı okumak daha açıklayıcıdır.'] },
      { heading: 'Güneş, Ay ve yükseleni ayrı değerlendirmek', paragraphs: ['Güneş karşılaştırması amaç ve kimlik temasına; Ay karşılaştırması güven, yakınlık ve duygusal tepkiye; yükselen karşılaştırması ilk temasın üslubuna odaklanır. Güneş’te ortaklık, Ay’daki bir ihtiyacı otomatik olarak çözmez. Yükselende farklılık da başlı başına anlaşmazlık değildir. Bu parçaları yan yana koymak, “Biz uyumlu muyuz?” sorusunu “Hangi alanlarda kolaylık, hangi alanlarda açıklık gerekiyor?” sorusuna dönüştürür.', 'Karşılaştırmada birinci ve ikinci kişinin sırası önemlidir. Aynı iki burç adı görülse bile açıklamanın hangi ihtiyacı kime bağladığı kontrol edilmelidir. Özellikle bir kişinin Güneş’i ile diğerinin Ay’ı karşılaştırıldığında amaç ve ihtiyaç görevlerini ters okumamak gerekir.'] },
      { heading: 'Benzerlik her zaman kolaylık değildir', paragraphs: ['Aynı ihtiyacı paylaşmak anlaşılmayı kolaylaştırabilir; ancak aynı savunmayı paylaşmak gerilimi büyütebilir. İki taraf da sessizleşiyorsa konuşma gecikebilir; ikisi de hızla tepki veriyorsa dinleme alanı daralabilir. Bunlar belirli bir burca mahkûm davranışlar değil, yorumun sınanabileceği ilişki sorularıdır. Farklılık ise bazen tamamlayıcıdır: biri seçenek üretirken diğeri devamlılık sağlayabilir. Tamamlayıcılığın işlemesi, karşılıklı rıza ve sorumluluk gerektirir.'] },
      { heading: 'Yorumun yerine geçemeyeceği şeyler', paragraphs: ['Uyum metni güvenilirlik, sadakat veya şiddet riski hakkında kanıt sunmaz. Bir davranış sizi incitiyorsa bunu astrolojik karşıtlık gerekçesiyle kabul etmeniz gerekmez. Karşılaştırmayı ilişkiyi başlatma veya bitirme talimatı olarak değil, konuşulabilecek ihtiyaçları ayıran bir çerçeve olarak kullanın. Somut davranışlar ve açık iletişim her zaman önceliklidir. Doğum bilgisi eksik olan birinin haritasını kesinmiş gibi yorumlamak da bu açıklığı bozar.'] },
    ],
  },
  {
    slug: 'dogum-saati-bilinmiyorsa', title: 'Doğum saatinizi bilmiyorsanız sonuçları nasıl değerlendirmelisiniz?',
    description: 'Saat uydurmadan belirsizliği yönetmek; Güneş, Ay, yükselen ve Kök Aks için ayrı güven sınırları belirlemek.',
    category: 'Hesaplama', sources: [method, engine], related: ['dogum-saati-yukseleni-nasil-etkiler', 'sinirda-doganlar-icin-kontrol'],
    sections: [
      { heading: 'Öğlen saati gerçek kaydın yerine geçmez', paragraphs: ['Doğum saati bilinmediğinde kutuya 12.00 yazmak teknik olarak bir sonuç üretebilir, fakat o sonuç varsayılan ana aittir. Programın kesin bir isim göstermesi, girilen bilginin kesin olduğu anlamına gelmez. Özellikle yükselen ve ondan türeyen Kök Aks, saate duyarlı olduğundan bu varsayım üzerinden kişisel hüküm kurulmaz. Bir alanı doldurmak ile doğru bilgi sağlamak arasındaki farkı korumak gerekir.'] },
      { heading: 'Bilinen ile bilinmeyeni ayırın', paragraphs: ['Önce elinizdeki kaydı değerlendirin: hastane belgesi mi, nüfus kaydı mı, aile hatırlaması mı? Kaynakların hassasiyeti aynı olmayabilir. “Sabaha karşı” gibi bir ifade tek dakikaya çevrilmemelidir. Olası bir zaman aralığı varsa, farklı saatlerde hesaplayarak hangi sonuçların değiştiğini görebilirsiniz. Hiçbir aralık bilinmiyorsa yükselen sonucunu öğrenilmiş bilgi gibi paylaşmamak daha doğrudur.', 'Bu çalışma saat düzeltmesi veya rektifikasyon yapmaz. Kişilik yorumunu okuyup “Bana bu daha çok uydu” diye doğum saati seçmek, hesabı bağımsız biçimde doğrulamaz. Önce veri, sonra hesap, en son yorum sırası korunmalıdır.'] },
      { heading: 'Güneş ve Ay için de ayrı kontrol gerekir', paragraphs: ['Güneş takımyıldızı birçok tarihte gün boyunca aynı kalabilir; ancak sınır geçişi olan bir günde saat sonucu etkileyebilir. Ay daha hızlı hareket ettiğinden gün içindeki değişim ayrıca kontrol edilmelidir. Aralığın başlangıç ve bitişinde aynı adı görmek ilk kontrol için yararlıdır; sınır yakınlığı varsa daha sık örnekleme gerekir. Yalnız bir hesap yapıp bütün gün için geçerli saymak belirsizliği gizler.'] },
      { heading: 'Paylaşımda hangi bilgiyi korumalı?', paragraphs: ['PDF veya sosyal medya kartını paylaşırken saatin yaklaşık olduğunu belirtmek, yorumun yanlış bir kesinlik kazanmasını önler. Doğum saatini sonradan öğrendiğinizde eski raporu yeni sonuçla karşılaştırın; eski kartın otomatik güncellendiğini varsaymayın. Saat dilimi ve konum da aynı kalmalıdır ki farkın nedenini anlayabilesiniz. Doğum kaydını doğrulayamıyorsanız kullanılabilecek en değerli çıktı, kesin görünen bir etiket değil, hangi yerleşimin belirsiz kaldığını açıkça bilmektir.'] },
    ],
  },
  {
    slug: 'yurtdisi-dogum-saat-dilimi', title: 'Yurt dışında doğanlar için konum ve saat dilimi kontrolü',
    description: 'Doğum yerini, yerel saati ve tarihsel UTC farkını ayırarak farklı ülkelerdeki kayıtları doğru girin.',
    category: 'Hesaplama', sources: [zones, method], related: ['dogum-saati-bilinmiyorsa', 'ayni-an-farkli-sehirler'],
    sections: [
      { heading: 'Bugünkü adresiniz değil, doğum yeriniz', paragraphs: ['Yurt dışında doğmuş birinin hesabında bugün yaşadığı ülke değil, doğumun gerçekleştiği yer esas alınır. Şehir adı benzerliklerine dikkat edilmelidir; farklı ülkelerde aynı adlı yerleşimler bulunabilir. Konum aramasındaki ülke ve koordinatları kontrol etmek bu nedenle önemlidir. Şehir bulunamazsa yakın görünen rastgele bir yeri seçmek yerine doğrulanmış enlem ve boylam kullanılmalıdır.'] },
      { heading: 'Yerel saat ile UTC farkını ayırın', paragraphs: ['Doğum belgesindeki saat genellikle o yerde kullanılan sivil saattir. Hesap için bu anın ortak zaman karşılığına çevrilmesi gerekir. America/New_York gibi bir bölge adı ile UTC-05:00 gibi sabit bir fark aynı bilgi değildir. Bölge, tarihe bağlı saat uygulamalarını temsil eder; sabit fark yalnız seçilen farkı uygular. Doğum tarihindeki uygulama bilinmeden bugünün farkını kullanmak hataya yol açabilir.', 'IANA veritabanı saat dilimlerinin tarihsel değişimlerini izler. Bununla birlikte tarayıcı ve işletim sisteminin kullandığı veri sürümü de önem taşır. Çok eski veya idari değişime yakın bir doğum kaydı söz konusuysa belge üzerindeki açık UTC bilgisi ve yerel resmî kayıt ayrıca incelenmelidir.'] },
      { heading: 'Saat ileri veya geri alındığında', paragraphs: ['Saatlerin ileri alındığı gün bazı yerel saatler yaşanmamış olabilir. Geri alındığı gün ise aynı saat iki farklı ana karşılık gelebilir. Bu durumda yalnız saat ve şehir bilgisi her zaman yeterli değildir. Kayıtta açık UTC farkı bulunuyorsa sabit fark seçeneğiyle o oluşum tanımlanabilir. Bilgi yoksa yazılımın birini sessizce seçmesi yerine belirsizliği korumak gerekir. Bir hata mesajını aşmak için dakikayı rastgele değiştirmeyin.'] },
      { heading: 'Sonuçtan önce kısa denetim', paragraphs: ['Tarihin gün ve ay sırasını kontrol edin; bazı belgeler ayı önce yazar. 12 saatlik kayıtlarda sabah ve akşam ayrımını doğrulayın. Koordinatlarda doğu-batı ve kuzey-güney işaretlerini ters girmeyin. Sonuçta gösterilen UTC anını kontrol ederek yerel tarihin bir önceki veya sonraki güne kaymasının normal olabileceğini unutmayın. Bu kontroller, yorumu değiştirmeden önce giriş verisini denetlemenizi sağlar.'] },
    ],
  },
  {
    slug: 'ayni-an-farkli-sehirler', title: 'Aynı anda farklı şehirlerde doğanların sonuçları neden değişir?',
    description: 'Dünya merkezli gök cismi konumu ile yerel ufuk hesabını ayırın; şehir seçiminin hangi sonucu etkilediğini görün.',
    category: 'Hesaplama', sources: [method, engine], related: ['yurtdisi-dogum-saat-dilimi', 'dogum-saati-yukseleni-nasil-etkiler'],
    sections: [
      { heading: 'Aynı saat ile aynı an farklıdır', paragraphs: ['İki doğum kaydında 10.00 yazması, doğumların aynı anda gerçekleştiğini göstermez. Şehirlerin saat dilimleri farklıysa bu iki yerel saat farklı UTC anlarına karşılık gelebilir. Buna karşılık aynı UTC anı, iki şehirde farklı saatlerle yazılır. Karşılaştırmaya başlamadan önce hangi tür eşitlikten söz ettiğinizi belirlemek gerekir. Aksi hâlde hem zaman hem yer değişirken ortaya çıkan fark yalnız şehre bağlanabilir.'] },
      { heading: 'Güneş ve Ay neden aynı kalabilir?', paragraphs: ['RealHoroscope Güneş ve Ay konumlarını Dünya merkezli hesaplar. Aynı UTC anı korunduğunda bu gökyüzü yönleri yalnız şehir seçildi diye değişmez. Ancak başka bir araç gözlemcinin yeryüzündeki konumunu da hesaba katan bir yaklaşım kullanabilir. Böyle bir karşılaştırmada yöntemin aynı olduğundan emin olun. İki yazılımın farklı gözlem başlangıçlarını kullanması, tek başına birinin yanlış olduğunu kanıtlamaz.'] },
      { heading: 'Yükselen ve Kök Aks yerel ufku izler', paragraphs: ['Yükselen, bulunduğunuz yerde ekliptiğin doğu ufkuyla ilişkisine bağlıdır. Enlem ve boylam değiştiğinde yerel ufuk da değişir. Kök Aks yükselenin karşısından türetildiği için bu değişimi izler. Dolayısıyla aynı anda farklı yerlerde doğan kişilerin Güneş ve Ay adları aynı, yükselen ve Kök Aks sonuçları farklı olabilir. Bu ayrım, illerin neden ayrı kişilik metinleri üretmek için değil, doğru yerleşimi hesaplamak için kullanıldığını açıklar.'] },
      { heading: 'Adil bir karşılaştırma nasıl yapılır?', paragraphs: ['Bir denemede yalnız tek değişkeni değiştirin. Yer etkisini görmek istiyorsanız aynı UTC anını koruyup koordinatları değiştirin. Saat etkisini görmek istiyorsanız koordinatları sabit tutun. Hem yerel saati hem şehri değiştirdiğinizde sonuç farkının kaynağını ayırmak zorlaşır. Şehir merkezinin doğum binanızın tam konumu olmadığını da hesaba katın; sınır yakınında daha kesin koordinatlarla yeniden bakmak yararlı olabilir.', 'Aynı yerleşim adlarının çıkması iki kişinin aynı hayatı yaşayacağı anlamına gelmez. Hesap gökyüzünün belirli bir andaki geometrisini verir; yorum ise bu geometriye ayrı anlamlar yükler. Yaşam koşulları ve tercihler bir şehir seçim listesinden çıkarılamaz.'] },
    ],
  },
  {
    slug: 'sinirda-doganlar-icin-kontrol', title: 'Takımyıldız sınırında doğanlar için sonuç kontrol rehberi',
    description: 'İki farklı sonuç gördüğünüzde tarih, UTC, koordinat ve referans sistemini hangi sırayla kontrol etmelisiniz?',
    category: 'Hesaplama', sources: [method, iau], related: ['burc-ve-takimyildiz-farki', 'dogum-saati-bilinmiyorsa'],
    sections: [
      { heading: 'İki isim görmek iki burca bölünmek değildir', paragraphs: ['Bir hesapta bir ad, başka bir hesapta başka ad görmek önce teknik olarak incelenmelidir. Araçlar aynı sistemi mi kullanıyor? Birinde tropikal dilim, diğerinde IAU bölgesi gösteriliyorsa isimler zaten farklı soruların cevaplarıdır. Aynı yöntemi kullanan araçlarda ise girilen zaman ve hesap ayarlarına bakılır. Sonucun değişmesini hemen “İki kişiliğim var” biçiminde yorumlamak hesabın nedenini açıklamaz.'] },
      { heading: 'Doğum kaydından başlayın', paragraphs: ['Önce yıl, ay, gün ve saati kontrol edin. Ardından doğum yerinin o tarihteki saat dilimine bakın. Yerel saatin UTC karşılığını not ederek başka araçta aynı anı kullanın. Ekrandaki yuvarlanmış saat veya derece, alttaki tam hesap değerinden farklı hassasiyette olabilir. Özellikle sınır yakınında dakika veya koordinat yuvarlaması etkili olabileceğinden yalnız ekran görüntüsündeki kısa etiketi karşılaştırmayın.'] },
      { heading: 'Referans ve gözlem noktası', paragraphs: ['Bir konumun hangi bölgeye düştüğünü denetlemek için koordinatların aynı referans sisteminde olması gerekir. Dünya merkezli ve gözlemci merkezli konumlar, özellikle Ay için aynı şey değildir. Ekliptik boylamı bir ekvatoryal koordinat gibi kullanmak da doğru değildir. Takımyıldız adını bulma işlemi, koordinat dönüşümü ve bölge sınırlarının birlikte ele alındığı bir hesap adımıdır.', 'Eşit 30 derecelik burç listesinden sayarak IAU karşıt noktasını bulmaya çalışmayın. Takımyıldız bölgeleri eşit genişlikte değildir. Karşıt nokta önce geometrik olarak hesaplanır; sonra hangi bölgeye düştüğü sorulur. İsim sırasından yapılan tahminin yanlış çıkması, karşıtlık geometrisinin bozuk olduğunu göstermez.'] },
      { heading: 'Düzeltme bildiriminde hangi bilgiler gerekli?', paragraphs: ['Bir hata bildiriminde kullanılan tarih-saat, saat dilimi, enlem-boylam, beklenen sonuç ve karşılaştırılan aracın yöntemi yeterli başlangıç sağlar. Kişisel belgenizin tamamını göndermeniz gerekmez; kimlik numarası veya adres gibi ilgisiz bilgileri paylaşmayın. Doğum saati yaklaşık ise bunu belirtin. Amaç yorumu size uygun bir etikete çevirmek değil, aynı verilerle tekrar üretilebilen bir farkı açıklamaktır. Karşılaştırma kaydı, yalnız “Burcum yanlış” ifadesinden çok daha değerlidir.'] },
    ],
  },
  {
    slug: 'gokyuzu-grafigini-okuma', title: 'Gökyüzü grafiğinde çizgiler, yaylar ve karşıt noktalar',
    description: 'Dünya merkezli şemayı adım adım okuyun; gök cismi yönünü, bölge yayını ve eksenleri birbirinden ayırın.',
    category: 'Başlangıç', sources: [axes, method], related: ['iau-takimyildiz-sinirlari', 'karanlik-ay-duygu-ekseni'],
    sections: [
      { heading: 'Merkez, bakış noktasını gösterir', paragraphs: ['Grafikte Dünya’nın merkezde olması, Güneş Sistemi’nin fiziksel merkezinin Dünya olduğu iddiası değildir. Şema, Dünya’dan bakılan yönleri düzenlemek için kurulmuştur. Güneş ve Ay simgeleri de gerçek uzaklıkları veya boyutlarıyla çizilmez. Bu nedenle grafiği bir uzay fotoğrafı gibi değil, belirli bir anın yön haritası gibi okumak gerekir. Simgenin merkezden uzaklığı bir kişilik ölçüsü değildir.'] },
      { heading: 'Renkli yaylar ve yerleşim işaretleri', paragraphs: ['Dış çemberin yayları, ekliptik boyunca karşılaşılan takımyıldız bölgelerini temsil eder. Yayların eşit olmaması bilinçli bir tercihtir; IAU bölgeleri on iki eşit dilim gibi davranmaz. Bir yerleşimi okumak için yalnız en yakın yazıya değil, o yerleşime ait işaret ve açıklamaya bakın. Yazılar okunabilirlik için yer değiştirmiş olabilir; hesaplanan noktanın açısı ile etiketin ekrandaki konumu aynı görevde değildir.'] },
      { heading: 'Üç karşıtlık birbirine karışmamalı', paragraphs: ['Güneş’in karşı yönünde Gölge Aks, yükselenin karşı yönünde Kök Aks, Ay’ın karşı yönünde Karanlık Ay Aksı bulunur. Her hat kendi başlangıç noktasından hesaplanır. Bu yüzden Kök Aks’ın Güneş’le aynı bölgede görünmesi mümkündür; Kök Aks zaten Güneş’in karşıtı olarak tanımlanmaz. Ay düğümleri ise bu üç hattın başka bir adı değildir. Grafik kalabalık gelirse önce tek hattı, ardından diğerlerini ayrı ayrı izleyin.'] },
      { heading: 'Ay için neden ek dikkat gerekir?', paragraphs: ['Ay ekliptik düzleminin tam üzerinde olmak zorunda değildir. Düz bir çember üzerindeki boylam gösterimi, üç boyutlu yönün bütün bilgisini taşımaz. Bu nedenle Ay simgesinin izdüşümüne yakın dış yay ile Ay’ın gerçek takımyıldız adı sınır yakınında farklı görünebilir. Kişisel sonuç kartındaki gerçek bölge adı korunmalı; varsa yorum için kullanılan izdüşüm ayrıca belirtilmelidir.', 'Grafik ile sonuç kartı arasında şüpheli bir fark görürseniz önce gösterim katmanlarını ayırın. Ardından aynı doğum bilgileriyle tekrar hesaplayıp ilgili noktanın adını kontrol edin. Yalnız görsel yakınlıktan hesap hatası sonucu çıkarmayın; fakat açıklanmayan bir tutarsızlığı da görmezden gelmeyin. Yöntem bağlantısı ve hata bildirim formu bu denetim için vardır.'] },
    ],
  },
];

const readingNotes: Record<string, GuideArticle['sections'][number]> = {
  'kok-aks-sakli-potansiyel': { heading: 'Potansiyelin kullanıldığını nasıl fark edersiniz?', paragraphs: ['Yorumda kendinize yakın bulduğunuz bir niteliği seçip onun yaşamınızdaki izini arayın. Daha önce hangi işte, ilişkide veya öğrenme sürecinde o beceriyi kullandınız? Bunu yalnız çevreniz sizi övdüğünde mi değerli sayıyorsunuz? Kullanılmayan potansiyel her zaman tamamen unutulmuş değildir; bazen tek bir alanda kullanılıp başka alanlara taşınmamıştır. Örneğin kişisel bir ilgideki düzen kurma becerisi, çalışma hayatında henüz değerlendirilmemiş olabilir.', 'Burada ölçü, açıklamanın ne kadar etkileyici duyulduğu değil, bir davranışı daha açık görmenize yardımcı olup olmadığıdır. Metin size uymuyorsa kendinizi ona uydurmak zorunda değilsiniz. Bir niteliği araştırmak ile o niteliğe sahip olduğunuzu kanıtlamaya çalışmak farklı şeylerdir. Gelişim, etiketin doğruluğunu savunmak yerine gerçek deneyiminizdeki kapasiteyi tanımakla başlar.'] },
  'gunes-kok-aks-ayni-burc': { heading: 'Aynı temaya iki farklı gelişim sorusu', paragraphs: ['Bu eşleşmede Güneş için “Kendimi neyle tanımlıyorum?”, Kök Aks için “Tanımladığım özelliği hangi beceriye dönüştürebiliyorum?” soruları birlikte kullanılabilir. “Ben bağımsızım” demek bir kimlik ifadesidir. Kendi kararının sorumluluğunu almak, yardım istemeyi de seçebilmek ve başladığını sürdürebilmek ise farklı becerilerdir. Ortak tema, bu becerilerin kendiliğinden tamamlandığını söylemez.', 'Yorumların çelişmemesi için Güneş bölümündeki güçlü yan Kök Aks bölümünde yokmuş gibi anlatılmaz. Bunun yerine aynı gücün henüz yeterince kullanılmayan boyutu açıklanır. Dolayısıyla “Bu özellik bende var” ile “Bu özelliği geliştirebilirim” aynı anda doğru olabilir. Saklı potansiyel vurgusu, benliğinizi reddetmez; onun görünen tarafıyla yetinmemeniz için bir okuma alanı açar.'] },
  'golge-aks-karsit-nitelikler': { heading: 'Karşıt niteliği almak, aşırılığı taklit etmek değildir', paragraphs: ['Sınır koymayı öğrenmek için sertleşmeniz, esnekliği öğrenmek için kararsızlaşmanız gerekmez. Gölge yorumunun olgun kullanımı, bir niteliğin hangi ölçüde yararlı olduğunu ayırt eder. Bunun için kendi tepkinizi, karşı tarafın davranışını ve ikinizin ihtiyaçlarını ayrı düşünün. Hepsini tek bir burç adına bağladığınızda somut mesele kaybolabilir.', 'Bir başka önemli ayrım da projeksiyondur: sizde tanımadığınız her özelliği başkasına yüklediğiniz varsayılmaz. İnsan bazen gerçekten uygun olmayan bir davranışa tepki verir. Astrolojik açıklama, yaşananları inkâr ettirmek için kullanılmamalıdır. Gölge Aks’ın sağladığı soru, tepkinizin tamamını yanlış ilan etmek değil, kabul edilebilir karşıt bir kapasiteye kendi yaşamınızda yer olup olmadığını araştırmaktır.'] },
  'karanlik-ay-duygu-ekseni': { heading: 'Duygusal sınavı bir gelişim cümlesine çevirmek', paragraphs: ['Bir ekseni okurken önce Ay’ın ihtiyacını tek cümlede özetleyin; ardından Karanlık Ay’ın önerdiği karşıt kapasiteyi başka bir cümlede ifade edin. İkisini “ama” ile birbirini çürütecek şekilde değil, “aynı zamanda” ile birlikte düşünün. Güvende olmak isteyebilir ve aynı zamanda değişime alan açabilirsiniz. Anlaşılmayı isteyebilir ve aynı zamanda karşı tarafın ayrı bir deneyimi olduğunu kabul edebilirsiniz.', 'Bu yaklaşım her duyguyu hemen çözmeyi vaat etmez. Özellikle baskı altında karşıt ihtiyacı duymak zaman alabilir. Harita, duygunuzu yaşamamanızı veya kendinizi zorla sakinleştirmenizi söylemez. Karanlık Ay temasının işe yarayan tarafı, ilk savunmanızdan sonra ikinci bir cevap seçme ihtimalini hatırlatmasıdır. Yorum bu nedenle bir olay tahmini değil, tepki alanını genişleten bir çerçevedir.'] },
  'kok-aks-ve-ay-dugumleri': { heading: 'Üç başlıkta aynı tema görünürse', paragraphs: ['Aynı nitelik birden fazla bölümde geçtiğinde açıklamayı görevine göre yeniden okuyun. Söz gelimi araştırma becerisi Kök Aks’ta kullanılmayı bekleyen bir kaynak, Güney düğüm yorumunda tanıdık bir yöntem, Kuzey düğüm yorumunda ise yeni bir alana taşınacak yaklaşım olarak ele alınabilir. Ortak kelimenin bulunması, hesaplanan noktaların birleştirildiği veya birbirine eşit olduğu anlamına gelmez.', 'Bir raporu değerlendirirken tekrarın açıklanıp açıklanmadığına bakın. Eğer bütün kartlar yalnız “Geçmişten gelen yetenek” diyorsa ayrım zayıflamıştır. Daha anlaşılır yorum, her başlığı kendi sorusuna geri bağlar ve kişinin hangi kapasiteyi tanıdığı, hangisine alışkanlıkla sığındığı, hangisini geliştirmek istediği arasında açık bir ilişki kurar. Bu ayrım, farklı burç adları kadar aynı adlar için de önemlidir.'] },
  'ayni-burc-farkli-yerlesimler': { heading: 'Birbirini destekleyen ve zorlayan okumalar', paragraphs: ['Tekrarlanan tema hedef, duygu ve davranış arasında kolay bir akış olarak okunabilir. Bunun yanında kişinin kendi bakışını sorgulamakta zorlanması da ele alınabilir. Yalnız güçlü tarafı anlatmak aşırı olumlu bir portre, yalnız riskleri sıralamak ise gereksiz bir kusur listesi oluşturur. Dengeli metin, niteliğin hangi koşulda işe yaradığını ve hangi koşulda daraldığını birlikte söyler.', 'Bu nedenle benzer yerleşimler için önerilen adımların farklı olması tutarsızlık değildir. Aynı kapasitenin hedef belirlerken, duygusal ihtiyaç anlatırken ve yeni bir ortama girerken farklı kullanımına işaret eder. Okuma sırasında her paragrafın başındaki yerleşim adını koruyun; bütün cümleleri genel bir kişilik hükmüne çevirerek birleştirmeyin.'] },
  'uyum-sonucunu-yuzdeye-indirmemek': { heading: 'İki tarafın geri bildirimi olmadan tamamlanmaz', paragraphs: ['Bir ilişki metnini yalnız kendi bakışınızdan onaylamak, karşı tarafın deneyimini göstermeyebilir. Karşılaştırmayı birlikte okuyorsanız hangi cümlelerin sizde karşılık bulduğunu ayrı ayrı ifade edin. Birinizin “Yakınlık istiyorum” dediği yerde diğeri “Sürekli hesap vermem bekleniyor” hissedebilir. Burç yorumunun görevi kimin haklı olduğunu ilan etmek değil, iki farklı anlamın konuşulmasını kolaylaştırmaktır.', 'Doğum bilgilerini paylaşmak istemeyen birini rapor üretmeye zorlamayın. Bir başkasının özel kaydını onun bilgisi dışında yayımlamak, uyum öğrenme amacını aşar. Sosyal paylaşım kartlarında isim, tam doğum zamanı veya konum bulunuyorsa yayımlamadan önce her iki kişinin onayını alın. İyi bir karşılaştırmanın sınırı yalnız hesap doğruluğu değil, kişilerin mahremiyeti ve seçim hakkıdır.'] },
  'dogum-saati-bilinmiyorsa': { heading: 'Belirsizlik aralığını kaydetmek', paragraphs: ['Aileniz yalnız bir saat aralığı hatırlıyorsa başlangıç ve bitişi not edin. Aynı tarih, yer ve saat dilimiyle birkaç olası anda hesap yapın. Hangi kartların değiştiğini yazın; değişmeyen kartların da yalnız denediğiniz aralık için aynı kaldığını unutmayın. Bu işlem doğum saatini bulmaz, mevcut belirsizliğin sonuç üzerindeki etkisini görünür kılar.', 'Yeni bir bilgi geldiğinde önce aralığı daraltın, sonra hesaplamayı tekrarlayın. Önceki yorumun hoşunuza gitmesi onu korumak için gerekçe değildir. Ayrıca saatteki belirsizliği dakikası tam görünen bir paylaşım kartının içine saklamayın. Kaydın yaklaşık olduğunu açıkça belirtmek, kullanıcı deneyimini zayıflatmaz; raporu daha doğru koşullarda okumayı sağlar.'] },
  'yurtdisi-dogum-saat-dilimi': { heading: 'Şehir listede yoksa hangi bilgi yeterli?', paragraphs: ['Bir şehrin hazır listede bulunmaması, o şehirde doğan kişi için hesap yapılamayacağı anlamına gelmez. Doğrulanmış koordinatlar ve uygun tarihsel saat dilimi sağlandığında aynı hesap yöntemi kullanılabilir. Önemli olan yer adının ekranda görünmesi değil, hesaplanan anın ve ufkun doğru tanımlanmasıdır. Çok yakın bir şehri seçmek bazı sonuçları değiştirmeyebilir; yine de özellikle sınır yakınında bunu kesin konum gibi sunmamak gerekir.', 'Konum araması birden fazla sonuç döndürdüğünde ülke, bölge ve haritadaki yer tutarlılığına bakın. Koordinatların yalnız sayısal aralık içinde bulunması doğru şehir olduklarını kanıtlamaz. Kontrolü yaptıktan sonra aynı girdilerle yeniden hesaplanabilecek bir kayıt tutun; tam adresinizi veya doğum belgenizi halka açık bir açıklamaya eklemeniz gerekmez.'] },
  'ayni-an-farkli-sehirler': { heading: 'Şehir adına göre ayrı karakter metni gerekir mi?', paragraphs: ['Hesaplama için çok sayıda şehir desteklemek, her şehre ayrı bir kişilik metni yazmayı gerektirmez. Yer bilgisi önce astronomik konuma dönüşür; yorum bundan sonra bulunan yerleşimler üzerinden seçilir. Aynı yerleşim kombinasyonuna ulaşan iki şehir için yalnız şehir adı değişen metinler üretmek kullanıcıya yeni bir anlam kazandırmaz. Üstelik yöntem, coğrafi isimden kişilik çıkardığı izlenimi verebilir.', 'Daha tutarlı yaklaşım hesap ve yorumu ayrı tutmaktır. Konum verisi doğru ufku, zaman verisi doğru anı belirler. Yorum motoru ise Güneş, Ay, yükselen ve aksların görevlerini birleştirir. Böylece Türkiye’de veya başka bir ülkede doğmuş olmak, yorumun kalitesini değil yalnız hesabın girdilerini değiştirir.'] },
  'sinirda-doganlar-icin-kontrol': { heading: 'Yuvarlama ile gerçek geçişi ayırt etmek', paragraphs: ['Bir noktanın ekranda tam sınır derecesi gibi görünmesi, hesapta gerçekten o sınır üzerinde bulunduğunu göstermez. Görünüm için yuvarlanan sayı iki farklı tam değeri aynı biçimde gösterebilir. Takımyıldız sorgusunun yuvarlanmamış konumu kullanması bu yüzden önemlidir. Karşılaştırmada ekran etiketini değil, mümkünse kullanılan tam koordinatı ve UTC anını esas alın.', 'Sonuç adının değişmesi de hareketin bir anda sıçradığı anlamına gelmez. Gök cismi sürekli ilerlerken bölge etiketi sınırda değişir. İdari bir sınırı geçen yolcunun konumu kesintisizdir, fakat bulunduğu bölgenin adı değişir. Bu benzetme yalnız bölge sorgusunu anlamaya yardımcı olur; kişinin karakterinin bir dakikada bütünüyle değiştiği yönünde bir iddia değildir.'] },
  'gokyuzu-grafigini-okuma': { heading: 'Grafik neden sade tutulur?', paragraphs: ['Bütün noktaları aynı anda açmak, daha çok bilgi gösterse de hangi çizginin hangi sonuca ait olduğunu izlemeyi zorlaştırabilir. İlk okumada Güneş, Ay ve yükselen yönleriyle başlayıp aksları sırayla eklemek daha anlaşılırdır. Bir hattı seçtiğinizde onun iki ucunu ve kartlardaki adları birlikte takip edin. Birbirine yakın noktaların etiketleri çakıştığında açıları değiştirmek yerine etiket düzeninin iyileştirilmesi gerekir.', 'Aynı burç adı farklı noktalarda tekrarlanabilir. Bu durumda çizgileri zorla farklı yaylara taşımak görseli temizlese de hesabı bozabilir. Doğru yaklaşım, hesaplanan yönleri korumak ve açıklamayı okunabilir sunmaktır. Çizimin sadeliği bilgi saklamak değil, her bilginin hangi katmana ait olduğunu ayırt edebilmek anlamına gelir.'] },
};

export const additionalArticles: GuideArticle[] = drafts.map(article => ({
  ...article, readTime: '', updated: '26 Eylül 2026',
  sections: [...article.sections, readingNotes[article.slug]],
  publishedAt: '2026-09-26', modifiedAt: '2026-09-26',
}));
