// RealHoroscope'un Kök Aks yaklaşımına özel editoryal, sembolik yorumlar.
export const rootReadings: Record<string, { short: string; text: string }> = {
 Ari: { short: 'Saklı gücünüz, cesaretinizi yeniden toplayıp ilk adımı atabilmek.', text: 'Kök Aks Koç, içinizde sessizce bekleyen girişim cesaretini anlatır. Geçmişte kendi başınıza yol bulurken geliştirdiğiniz kararlılığı bugün sıradan bir dayanıklılık gibi görebilirsiniz. Oysa koşullar netleşmeden de yön seçebilmek, yeniden kullanabileceğiniz bir yetenektir. Kendinizi kanıtlamak için acele etmeniz gerekmez; gerçekten istediğiniz bir başlangıca sahip çıkmanız bu gücü görünür kılar.' },
 Tau: { short: 'Saklı gücünüz, sabırla emek verip kalıcı bir değer oluşturabilmek.', text: 'Kök Aks Boğa, elinizdekini büyütme ve hayatınıza sağlam bir zemin kurma potansiyelinizi anlatır. Geçmişte sabır isteyen süreçlerden edindiğiniz becerileri, herkesin yapabileceği şeyler sanarak küçümseyebilirsiniz. Buradaki yetenek yalnızca dayanmak değil, neyin korunmaya değer olduğunu bilmektir. Emek verdiğiniz bir işi yeniden sahiplenmek, içinizde sönük kalmış üretkenliği canlandırabilir.' },
 Gem: { short: 'Saklı gücünüz, öğrendikleriniz arasında yeni bağlantılar kurabilmek.', text: 'Kök Aks İkizler, farklı deneyimleri birbirine bağlayan zihinsel çevikliğinizi anlatır. Bir zamanlar öğrendiğiniz, sonra kullanmadığınız bilgiler düşündüğünüzden daha zengin bir birikim oluşturabilir. Sözü anlaşılır kılmak, doğru soruyu sormak ve bir konuya başka açıdan bakmak burada saklı duran yeteneklerdir. Merakınızı yeniden izlediğinizde, dağınık sandığınız deneyimlerin ortak bir dil bulduğunu görebilirsiniz.' },
 Cnc: { short: 'Saklı gücünüz, incelikleri fark ederek güven veren bir alan kurabilmek.', text: 'Kök Aks Yengeç, geçmiş deneyimlerin içinizde bıraktığı duygusal sezgiyi anlatır. Bir ortamın havasını anlamak ve söze dökülmeyen ihtiyacı fark etmek size o kadar doğal gelebilir ki bunu bir yetenek olarak görmeyebilirsiniz. Bu birikim, kendinizi unutarak herkesi korumanızı istemez. Kendi ihtiyaçlarınıza da aynı özeni gösterdiğinizde, güven veren ve bağları besleyen yanınız daha rahat ortaya çıkar.' },
 Leo: { short: 'Saklı gücünüz, yaratıcılığınızı sahiplenip ona görünür bir biçim verebilmek.', text: 'Kök Aks Aslan, geri planda tuttuğunuz yaratıcı cesareti ve sıcaklığı anlatır. Geçmişte kendinizi ifade ederken edindiğiniz beceriler, takdir görmedikleri dönemlerde sessizleşmiş olabilir. Bu yerleşim, değerinizi sürekli alkışla ölçmek yerine ortaya koymaktan keyif aldığınız şeyi hatırlatır. Bir fikre kendi renginizi katmanız, uzun süredir kullanmadığınız anlatma ve ilham verme gücünü yeniden uyandırabilir.' },
 Vir: { short: 'Saklı gücünüz, ayrıntıları görüp karmaşaya işler bir düzen verebilmek.', text: 'Kök Aks Başak, deneyimle incelmiş dikkatinizi ve bir şeyi daha iyi hâle getirme becerinizi anlatır. Başkalarının atladığı ayrıntıları fark etmeniz size olağan görünebilir; oysa bu, zaman içinde geliştirilmiş değerli bir ustalıktır. Yeteneğinizin görünmesi için kusursuz olmanız gerekmez. Bildiklerinizi somut bir işe aktardığınızda, eleştiriye dönüşen dikkat yeniden üretken bir güce kavuşur.' },
 Lib: { short: 'Saklı gücünüz, farklı bakışları anlayıp adil bir denge kurabilmek.', text: 'Kök Aks Terazi, deneyimlerinizle gelişmiş ölçü duygusunu ve uzlaştırma yeteneğini anlatır. Birbirine uzak görüşler arasında ortak bir dil bulmanız, farkına varmadığınız bir beceriniz olabilir. Bu güç, kendi isteğinizi silerek herkesi memnun etmek değildir. Kendi duruşunuzu da masaya koyduğunuzda, hem ilişkilerde hem ürettiklerinizde uyum ve hakkaniyet yaratma potansiyeliniz belirginleşir.' },
 Sco: { short: 'Saklı gücünüz, zor deneyimlerden derin bir kavrayış çıkarabilmek.', text: 'Kök Aks Akrep, kolay görünmeyenin altına bakma ve zor bir sürecin içinden anlam çıkarma potansiyelinizi anlatır. Geçmiş deneyimlerden kalan dikkat ve sezgiyi yalnızca bir korunma biçimi sanabilirsiniz. Oysa aynı birikim, karmaşık duyguları anlamanıza ve yarım kalmış meseleleri dürüstçe ele almanıza da yardım edebilir. Gücünüz her şeyi kontrol etmekte değil, derinliği taşıyabildiğinizi fark etmekte saklıdır.' },
 Oph: { short: 'Saklı gücünüz, yaşadıklarınızdan öğrenerek yeni bir yol açabilmek.', text: 'Kök Aks Yılancı, değişimin içinden öğrendiklerinizi yeni bir anlayışa dönüştürme yeteneğini anlatır. Geride bıraktığınız süreçlerin size kazandırdığı kavrayış, henüz adını koymadığınız bir potansiyel olabilir. Burada değerli olan herkesi kurtarmak değil, neyin artık işlemediğini görüp başka bir yol kurabilmektir. Deneyiminizi küçümsemeden ve size ait olmayan yükleri üstlenmeden kullandığınızda, onarıcı yanınız güç kazanır.' },
 Sgr: { short: 'Saklı gücünüz, deneyimlerinize geniş açıdan bakıp yeniden yön bulabilmek.', text: 'Kök Aks Yay, yaşadıklarınızı daha geniş bir çerçevede anlamlandırma potansiyelinizi anlatır. Zaman içinde biriken bilgileriniz ve karşılaştığınız farklı bakışlar, henüz paylaşmadığınız bir bilgelik taşıyabilir. Bu yetenek her soruya cevap vermek değil, daralmış bir bakışa yeni bir pencere açmaktır. Öğrenme ve anlatma isteğinizi yeniden izlediğinizde, geri planda kalan umut ve yön bulma gücünüz canlanabilir.' },
 Cap: { short: 'Saklı gücünüz, deneyiminizi sabırlı ve sağlam bir yapıya dönüştürebilmek.', text: 'Kök Aks Oğlak, geçmiş deneyimlerle olgunlaşmış yapı kurma ve sorumluluk taşıma becerinizi anlatır. Zorunluluk diye gördüğünüz bazı çabaların size bir ustalık kazandırdığını fark etmeyebilirsiniz. Buradaki potansiyel daha fazla yük almak değil, emeğinizi gerçekten değer verdiğiniz bir hedefe yöneltebilmektir. Neyi sürdürebildiğinizi ve nerede sınır koyduğunuzu gördükçe, sessiz gücünüz daha görünür olur.' },
 Aqr: { short: 'Saklı gücünüz, alışılmışın dışında düşünüp yeni bir seçenek görebilmek.', text: 'Kök Aks Kova, deneyimlerinizden süzülmüş bağımsız düşünme ve farklı bağlantılar kurma yeteneğini anlatır. Bir zamanlar çevrenize uymadığı için geri çektiğiniz fikirler, bugün değerli bir katkının başlangıcı olabilir. Bu güç, farklı görünmeye çalışmaktan çok kendi bakışınıza güvenmenizle açılır. Bildik bir soruya kendi sorularınızla yaklaştığınızda, kullanılmadan bekleyen yenilikçi yanınız yeniden hareket kazanır.' },
 Psc: { short: 'Saklı gücünüz, sezginizi ve hayal gücünüzü anlamlı bir ifadeye dönüştürebilmek.', text: 'Kök Aks Balık, geçmiş deneyimlerin beslediği sezgiyi, hayal gücünü ve duyarlılığı anlatır. Söze dökemediğiniz bir izlenimi anlamak ya da başkasının duygusuna incelikle yaklaşmak, önemini fark etmediğiniz bir yetenek olabilir. Bu potansiyel kendinizi başkalarının içinde kaybetmenizi istemez. Hissettiklerinize bir ifade alanı açtığınızda, uzun süredir sessiz kalan yaratıcı ve şefkatli yanınız yeniden güç bulabilir.' },
};
