import { rootReadings } from './root-readings';

// Editorial interpretation only. This module never changes astronomical positions.
const integration: Record<string, { talent: string; text: string; practice: string }> = {
  Ari: { talent: 'başlatma cesaretinizi kararlı bir girişime dönüştürmek', text: 'Cesareti kimliğinizin bir parçası olarak tanıyabilirsiniz; onu kendi yolunuzu kurmak için kullanmak ise başka bir olgunluk ister. İçinizdeki öncü güç, yalnız itiraz ederken değil, sorumluluğunu üstlendiğiniz bir başlangıçta açılır. Her mücadeleye atılmak yerine sizin için anlamlı olanı seçmeniz, saklı girişim yeteneğinizi görünür kılar.', practice: 'Ertelediğiniz bir başlangıç için başkasının onayını beklemeden üstlenebileceğiniz ilk sorumluluğu belirleyin ve tamamlayın.' },
  Tau: { talent: 'sabır ve değer duygunuzu üretken bir beceriye dönüştürmek', text: 'Sağlam durmayı biliyor olmanız, üretme gücünüzü bütünüyle kullandığınız anlamına gelmez. Bazen koruduğunuz düzen, elinizdeki yeteneğin gelişmesini de yavaşlatır. Kökünüzdeki birikim, yalnız sahip olduklarınızı tutmak için değil, onlara yeni değer katmak için vardır. Kendi emeğinizin niteliğine güvenmeniz, güven arayışınızı verimli bir zemine taşır.', practice: 'Elinizin yatkın olduğu bir işi seçin; bu hafta yalnız korumak yerine geliştireceğiniz tek bir somut parçasını bitirin.' },
  Gem: { talent: 'merakınızı derinleşen bilgiye ve açık anlatıma dönüştürmek', text: 'Zihninizin hareketliliği görünür olabilir; fakat öğrendikleriniz arasında bağ kurma ustalığınızı sıradan sayabilirsiniz. Burada potansiyel, daha çok konu bilmekten ziyade dağınık bilgiyi başkasının anlayacağı bir dile çevirmektir. İlginizi taşıyacak bir odak seçmeniz, konuşkanlığın gerisindeki güçlü anlatıcıyı ve araştırmacıyı ortaya çıkarır.', practice: 'Bildiğiniz bir konuyu hiç bilmeyen biri için kısa bir açıklamaya dönüştürün; eksik kaldığınız tek noktayı araştırarak tamamlayın.' },
  Cnc: { talent: 'duyarlılığınızı sınırları olan bir bakım ve bağ kurma gücüne dönüştürmek', text: 'Yakınlık kurma isteğinizi tanısanız da bir ortamın ihtiyacını sezme becerinizi yeterince önemsemeyebilirsiniz. İçinizdeki koruyucu güç, herkesi üzerinize almak zorunda olduğunuz anlamına gelmez. Kendi duygusal sınırınız da bu yeteneğin parçasıdır. Neyin size, neyin başkasına ait olduğunu ayırt ettikçe şefkatiniz yük taşımaktan güven veren bir varoluşa dönüşür.', practice: 'Özen gösterdiğiniz bir ilişkide neyi gönüllü yaptığınızı ve nerede dinlenmeye ihtiyaç duyduğunuzu ayrı ayrı ifade edin.' },
  Leo: { talent: 'yaratıcı cesaretinizi dış onaya bağlı kalmadan ortaya koymak', text: 'Görünür olmayı isteyebilirsiniz; ancak asıl potansiyeliniz ilgi çekmekten önce kendinize ait bir ifadeyi sahiplenmektir. Takdir beklerken geri tuttuğunuz yaratıcı taraf, denemeye izin verdiğinizde güçlenir. Güneş ile Kök Aks’ın ortak vurgusu size başka biri olmayı değil, taşıdığınız sıcaklığı ve üretme cesaretini kendi ölçünüzle kullanmayı hatırlatır.', practice: 'Beğenilip beğenilmeyeceğini ölçmeden önce size ait küçük bir yaratıcı çalışmayı tamamlayın; neyi ifade ettiğini kendiniz adlandırın.' },
  Vir: { talent: 'ayırt etme becerinizi kusur aramaktan yararlı bir ustalığa taşımak', text: 'Ayrıntıları görmeniz zaten tanıdık bir özelliğiniz olabilir; fakat bu dikkatin değerini yalnız hataları giderirken fark ediyor olabilirsiniz. Saklı ustalığınız, karmaşık bir şeyi anlaşılır ve işler hâle getirmektir. Yeterli olanı kabul edebildiğinizde dikkatiniz kendinizi yargılayan bir sese değil, emek verdiğiniz işi geliştiren bir beceriye dönüşür.', practice: 'Karmaşık bulduğunuz bir işi üç uygulanabilir aşamaya ayırın; ilk aşamayı kusursuzlaştırmadan kullanılabilir hâle getirin.' },
  Lib: { talent: 'uyum arayışınızı kendi duruşunuzu koruyan bir uzlaştırma gücüne dönüştürmek', text: 'İlişkilerde denge istemekle gerçekten adil bir denge kurmak aynı şey değildir. Kökünüzdeki ölçü duygusu, yalnız karşı tarafı anlamanızı değil, kendi payınızı da hesaba katmanızı ister. Hoşnutsuzluk yaratmaktan kaçınırken sakladığınız fikri dile getirmek, uzlaştırma yeteneğinizi zayıflatmaz; ona içtenlik ve ağırlık kazandırır.', practice: 'Ortak bir kararda iki tarafın isteğini yazdıktan sonra kendi vazgeçemeyeceğiniz koşulu açıkça belirtin.' },
  Sco: { talent: 'derin kavrayışınızı kontrol yerine dönüşüm için kullanmak', text: 'Yoğunluğunuzu tanıyor olabilirsiniz; fakat zor olanın içine bakma dayanıklılığınızı yalnız bir korunma refleksi gibi görmeniz mümkündür. İçinizdeki güç, her ihtimali denetlemekten çok, gerçeği gördüğünüzde yön değiştirebilmenizde yatar. Kökünüzde taşıdığınız sezgiyi kanıt ve açıklıkla buluşturduğunuzda, kuşkuya harcanan enerji kavrayışa dönüşür.', practice: 'Kontrol etmeye çalıştığınız bir konuda bildiğiniz gerçekleri varsayımlarınızdan ayırın; yalnız kendi sorumluluğunuzdaki adımı seçin.' },
  Oph: { talent: 'değişimden öğrendiklerinizi işe yarayan bir yönteme dönüştürmek', text: 'Yenilenme isteğiniz güçlü olabilir; asıl birikiminiz ise yaşadığınız değişimlerden hangi dersin taşınabileceğini ayırt etmektir. Her krizi çözmeniz veya herkesi iyileştirmeniz gerekmez. Kökünüzdeki onarıcı potansiyel, sınırlarınızı koruyarak öğrendiğinizi somut bir yönteme dönüştürdüğünüzde açılır. Böylece dönüşüm, sürekli yeniden başlamak olmaktan çıkar ve birikim kazanır.', practice: 'Geride bıraktığınız bir süreçte gerçekten işe yarayan yöntemi yazın; onu bugünkü tek bir meseleye uyarlayın.' },
  Sgr: { talent: 'anlam arayışınızı deneyime dayanan bir rehberliğe dönüştürmek', text: 'Büyük resmi görmek size doğal gelebilir; fakat görüşünüzü somut deneyimle besleme sabrını ikinci planda bırakabilirsiniz. Kökünüzdeki yetenek, her soruya cevap vermek değil, öğrenileni anlaşılır bir yöne çevirmektir. Bildiklerinizi sorgulamaya açık tutmanız, düşüncenizin etkisini azaltmaz; anlatınıza güven ve derinlik kazandırır.', practice: 'Güçlü savunduğunuz bir düşünceyi kendi deneyiminizden bir örnekle açıklayın; sonra henüz bilmediğiniz sınırını da ekleyin.' },
  Cap: { talent: 'dayanıklılığınızı anlamlı hedeflere hizmet eden bir yapı kurma gücüne dönüştürmek', text: 'Sorumluluk almak kimliğinizin tanıdık tarafı olabilir; fakat kendinize ait bir yapı kurma becerinizi yalnız yük taşımakla karıştırabilirsiniz. Saklı potansiyeliniz daha çok çalışmak değil, emeği doğru yere yerleştirmektir. Önceliklerinizi siz belirlediğinizde, birikmiş disiplininiz başkalarının beklentisini sürdürmek yerine kendi hedefinize zemin hazırlar.', practice: 'Sürdürdüğünüz bir sorumluluğu değerlendirin: hedefinize hizmet etmeyen kısmını azaltıp açılan zamanı kendi projenize ayırın.' },
  Aqr: { talent: 'bağımsız bakışınızı paylaşılabilir bir yeniliğe dönüştürmek', text: 'Farklı düşünebildiğinizi bilmeniz, o düşünceyi hayata geçirdiğiniz anlamına gelmez. İçinizdeki yenilikçi güç, yalnız mevcut düzene mesafe koyarken değil, daha iyi bir seçeneği başkalarının da kullanabileceği biçimde kurarken görünür olur. Kökünüzdeki özgünlüğü anlaşılır kılmanız, bağımsızlığınızdan vazgeçmek değil, ona etki alanı açmaktır.', practice: 'Alışılmış bulduğunuz bir soruna önerdiğiniz çözümün küçük bir örneğini hazırlayın ve bir kişiden kullanılabilirliği hakkında geri bildirim alın.' },
  Psc: { talent: 'sezgi ve hayal gücünüzü sınırları olan yaratıcı bir ifadeye dönüştürmek', text: 'Duyarlılığınız görünürken onu bir ürüne, söze veya karara dönüştürme yeteneğiniz gölgede kalabilir. Kökünüzdeki potansiyel, her duyguyu yüklenmek değil, hissettiklerinize anlamlı bir biçim verebilmektir. Kendi alanınızı korumanız sezginizi azaltmaz; hangi izlenimin size ait olduğunu duymanızı sağlar. Yaratıcılığınız bu açıklıkta daha güvenli bir yer bulur.', practice: 'Söze dökmekte zorlandığınız bir duyguyu kısa bir metin, çizim veya melodiyle ifade edin; başkasının beklentisine göre düzeltmeden önce tamamlayın.' },
};

export function rootIntegration(rootIau: string, sunIau: string) {
  const base = rootReadings[rootIau];
  const item = integration[rootIau];
  const same = rootIau === sunIau && !!base && !!item;
  return {
    same,
    text: same
      ? `Güneşiniz ile Kök Aks’ınız aynı burçta. Bu tekrar, bütün potansiyelinizi zaten kullandığınızı değil, benliğinizde tanıdığınız bir niteliğin daha derin bir beceriye dönüşmeyi beklediğini anlatır. ${item.text} Gelişim yönünüz, başka bir kişiliğe bürünmekten çok, zaten içinizde bulunan bu gücü bilinçli ve tutarlı kullanmayı öğrenmektir.`
      : base?.text ?? 'Kök Aks, içinizde mevcut olan fakat henüz yeterince fark etmediğiniz potansiyeli anlatır.',
    short: same
      ? `Güneş ve Kök Aks aynı burçta: saklı potansiyelinizi kullanmayı öğrenmeniz, ${item.talent} üzerinden gelişir.`
      : base?.short ?? 'Kök Aks, içinizde taşıdığınız saklı potansiyeli anlatır.',
    practice: item?.practice,
  };
}
